### PR TITLE
[SOW MS3] Set magma backend for meta tests

### PR DESCRIPTION
**Pull request by alugorey**
Fixes https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/2397

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
jenkins retest this please

**Review by jithunnair-amd — APPROVED** [review]
LGTM. Waiting for CI

**Comment by jithunnair-amd** [comment]
jenkins retest this please

**Comment by jithunnair-amd** [comment]
jenkins retest this please

**Comment by jithunnair-amd** [comment]
^^ trying with `${ghprbActualCommit}` as "Branches to build" for pytorch-build to see if that results in a merge with sow_ms3 branch. The last CI job http://rocmhead.amd.com:8080/job/pytorch/job/pytorch-ci/290/ failed because it is just trying to build this PR branch without merging in changes from sow_ms3 (which include a revert of the faulty commit), resulting in build failure,

**Comment by jithunnair-amd** [comment]
@alugorey Sorry, I am trying to resolve the issue of pytorch-build CI job not doing a merge of the target branch, so for now, you'll need to rebase this on sow_ms3 to make sure the revert of your PR 1080 is in the PR branch itself, otherwise the CI build will continue to break

**Comment by alugorey** [comment]
@jithunnair-amd Done! sorry about that!

**Comment by jithunnair-amd** [comment]
jenkins retest this please

**Comment by jithunnair-amd** [comment]
From https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/2397#issuecomment-1227363320:
```
Results of running tests with patch

root@92a38368bccd:/home/pytorch# python test/test_meta.py TestMetaCUDA.test_dispatch_meta_linalg_svdvals_cuda_complex128
[W Context.cpp:199] Warning: torch.backends.cuda.preferred_linalg_library is an experimental feature. If you see any error or unexpected behavior when this flag is set please file an issue on GitHub. (function operator())
.
----------------------------------------------------------------------
Ran 1 test in 3.623s

OK
root@92a38368bccd:/home/pytorch# python test/test_meta.py TestMetaCUDA.test_dispatch_meta_linalg_svdvals_cuda_complex64
[W Context.cpp:199] Warning: torch.backends.cuda.preferred_linalg_library is an experimental feature. If you see any error or unexpected behavior when this flag is set please file an issue on GitHub. (function operator())
.
----------------------------------------------------------------------
Ran 1 test in 3.441s

OK
root@92a38368bccd:/home/pytorch# python test/test_meta.py TestMetaCUDA.test_dispatch_meta_linalg_svdvals_cuda_float32
[W Context.cpp:199] Warning: torch.backends.cuda.preferred_linalg_library is an experimental feature. If you see any error or unexpected behavior when this flag is set please file an issue on GitHub. (function operator())
.
----------------------------------------------------------------------
Ran 1 test in 3.533s

OK
root@92a38368bccd:/home/pytorch# python test/test_meta.py TestMetaCUDA.test_dispatch_meta_linalg_svdvals_cuda_float64
[W Context.cpp:199] Warning: torch.backends.cuda.preferred_linalg_library is an experimental feature. If you see any error or unexpected behavior when this flag is set please file an issue on GitHub. (function operator())
.
----------------------------------------------------------------------
Ran 1 test in 3.571s

OK
root@92a38368bccd:/home/pytorch# python test/test_meta.py TestMetaCUDA.test_meta_linalg_svdvals_cuda_complex128
[W Context.cpp:199] Warning: torch.backends.cuda.preferred_linalg_library is an experimental feature. If you see any error or unexpected behavior when this flag is set please file an issue on GitHub. (function operator())
.
----------------------------------------------------------------------
Ran 1 test in 3.624s

OK
root@92a38368bccd:/home/pytorch# python test/test_meta.py TestMetaCUDA.test_meta_linalg_svdvals_cuda_complex64
[W Context.cpp:199] Warning: torch.backends.cuda.preferred_linalg_library is an experimental feature. If you see any error or unexpected behavior when this flag is set please file an issue on GitHub. (function operator())
.
----------------------------------------------------------------------
Ran 1 test in 3.535s

OK
root@92a38368bccd:/home/pytorch# python test/test_meta.py TestMetaCUDA.test_meta_linalg_svdvals_cuda_float32
[W Context.cpp:199] Warning: torch.backends.cuda.preferred_linalg_library is an experimental feature. If you see any error or unexpected behavior when this flag is set please file an issue on GitHub. (function operator())
.
----------------------------------------------------------------------
Ran 1 test in 3.666s

OK
root@92a38368bccd:/home/pytorch# python test/test_meta.py TestMetaCUDA.test_meta_linalg_svdvals_cuda_float64
[W Context.cpp:199] Warning: torch.backends.cuda.preferred_linalg_library is an experimental feature. If you see any error or unexpected behavior when this flag is set please file an issue on GitHub. (function operator())
.
----------------------------------------------------------------------
Ran 1 test in 3.442s

OK
Tested with rocm/pytorch-private:rocm5.2_ubuntu20.04_py3.7_pytorch_sow_ms3
```

**Comment by jithunnair-amd** [comment]
From https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/2338#issuecomment-1227410716:
```
Both tests pass with https://github.com/ROCmSoftwarePlatform/pytorch/pull/1087 fix

root@92a38368bccd:/home/pytorch# python test/test_ops.py TestCommonCUDA.test_out_linalg_svdvals_cuda_float32
.
----------------------------------------------------------------------
Ran 1 test in 5.350s

OK
root@92a38368bccd:/home/pytorch# python test/test_ops.py TestCommonCUDA.test_out_warning_linalg_svdvals_cuda
.
----------------------------------------------------------------------
Ran 1 test in 4.398s

OK
```

**Pull request merged**
