### PR TITLE
IFU-main-2023-06-06

### PR DESCRIPTION
**Pull request by pruthvistony**
No Conflicts

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
The Pytorch build actually succeeded: http://rocmhead:8080/job/pytorch/job/pytorch-build/809/console
3 out of 4 PyTorch test CI jobs completed:
[pytorch-test-2](http://rocmhead:8080/job/pytorch/job/pytorch-test-2/694/console): `functorch/test_eager_transforms.py::TestCompileTransformsCUDA::test_compile_vmap_hessian_cuda` failed due to triton not built inside docker image. This is because we are using `rocm/pytorch:latest` as the base docker image and it doesn't have triton built as part of it. Created a story to work on this, but it needn't block this IFU: https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/4635
[pytorch-test-distributed-1](http://rocmhead:8080/job/pytorch/job/pytorch-test-distributed-1/668/console): Looks like all UTs passed
[pytorch-test-distributed-2](http://rocmhead:8080/job/pytorch/job/pytorch-test-distributed-2/661/console): Looks like all UTs passed

1 out of 4 ([pytorch-test-1](http://rocmhead:8080/job/pytorch/job/pytorch-test-1/693/console)) hung and timed out. Did you observe the same in your local run?

**Comment by pruthvistony** [comment]
Looking at the test1 output

01:26:21 Jun 06 19:56:18 test_ops_gradients.py::TestBwdGradientsCUDA::test_inplace_gradgrad_zeros_like_cuda_complex128 SKIPPED [0.0004s] (Skipped! Op doesn't support autograd for this dtype.) [ 99%]
01:26:21 Jun 06 19:56:18 test_ops_gradients.py::TestBwdGradientsCUDA::test_inplace_gradgrad_zeros_like_cuda_float64 SKIPPED [0.0004s] (Skipped! Op doesn't support autograd for this dtype.) [100%]
01:26:21 Jun 06 19:56:18 
01:26:21 Jun 06 19:56:18 - generated xml file: /var/lib/jenkins/pytorch/test/test-reports/python-pytest/test_ops_gradients/test_ops_gradients-9f9b96903c82c50c.xml -
01:26:21 Jun 06 19:56:18 ========= 1919 passed, 3141 skipped, 43 xfailed in 2459.19s (0:40:59) ==========

It seems like test setup issue, where the next test file didnt start execution.

I ran few individual test files and it was fine. May be will try running the test.sh on MI200.

However I feel the CI results are good enough to merge this PR, IHOP.

**Review by jithunnair-amd — APPROVED** [review]
LGTM. test1 issues seem to be due to faulty CI node.

**Comment by pruthvistony** [comment]
test1 executed on - 

ixt-rack-169
dmesg shows lot of amdgpu error logs and dont see any watchdog or doorbell errors...

**Comment by pruthvistony** [comment]
Few failures seen on local run on MI200

=========================== short test summary info ============================
FAILED [0.0501s] test_ops.py::TestCommonCPU::test_python_ref_meta__refs_linalg_svd_cpu_complex128 - RuntimeError: Conj mismatch! is_conj is set to False and True
FAILED [0.0500s] test_ops.py::TestCommonCPU::test_python_ref_meta__refs_linalg_svd_cpu_complex64 - RuntimeError: Conj mismatch! is_conj is set to False and True
FAILED [0.0029s] test_ops.py::TestCommonCUDA::test_complex_half_reference_testing_nn_functional_conv_transpose3d_cuda_complex32 - AssertionError: Tensor-likes are not close!


=========================== short test summary info ============================
FAILED [0.0079s] test_torch.py::TestTorchDeviceTypeCPU::test_storage_meta_errors_cpu_bfloat16 - TypeError: cannot pin 'torch.storage.UntypedStorage' only CPU memory can be pinned
FAILED [0.0079s] test_torch.py::TestTorchDeviceTypeCPU::test_storage_meta_errors_cpu_bool - TypeError: cannot pin 'torch.storage.UntypedStorage' only CPU memory can be pinned
FAILED [0.0079s] test_torch.py::TestTorchDeviceTypeCPU::test_storage_meta_errors_cpu_complex128 - TypeError: cannot pin 'torch.storage.UntypedStorage' only CPU memory can be pinned
FAILED [0.0079s] test_torch.py::TestTorchDeviceTypeCPU::test_storage_meta_errors_cpu_complex64 - TypeError: cannot pin 'torch.storage.UntypedStorage' only CPU memory can be pinned
FAILED [0.0079s] test_torch.py::TestTorchDeviceTypeCPU::test_storage_meta_errors_cpu_float16 - TypeError: cannot pin 'torch.storage.UntypedStorage' only CPU memory can be pinned
FAILED [0.0079s] test_torch.py::TestTorchDeviceTypeCPU::test_storage_meta_errors_cpu_float32 - TypeError: cannot pin 'torch.storage.UntypedStorage' only CPU memory can be pinned
FAILED [0.0079s] test_torch.py::TestTorchDeviceTypeCPU::test_storage_meta_errors_cpu_float64 - TypeError: cannot pin 'torch.storage.UntypedStorage' only CPU memory can be pinned
FAILED [0.0079s] test_torch.py::TestTorchDeviceTypeCPU::test_storage_meta_errors_cpu_int16 - TypeError: cannot pin 'torch.storage.UntypedStorage' only CPU memory can be pinned
FAILED [0.0079s] test_torch.py::TestTorchDeviceTypeCPU::test_storage_meta_errors_cpu_int32 - TypeError: cannot pin 'torch.storage.UntypedStorage' only CPU memory can be pinned
FAILED [0.0079s] test_torch.py::TestTorchDeviceTypeCPU::test_storage_meta_errors_cpu_int64 - TypeError: cannot pin 'torch.storage.UntypedStorage' only CPU memory can be pinned
FAILED [0.0079s] test_torch.py::TestTorchDeviceTypeCPU::test_storage_meta_errors_cpu_int8 - TypeError: cannot pin 'torch.storage.UntypedStorage' only CPU memory can be pinned
FAILED [0.0079s] test_torch.py::TestTorchDeviceTypeCPU::test_storage_meta_errors_cpu_uint8 - TypeError: cannot pin 'torch.storage.UntypedStorage' only CPU memory can be pinned
====== 12 failed, 1457 passed, 93 skipped, 24 rerun in 112.84s (0:01:52) =======

**Pull request merged**
