### PR TITLE
Fix the PyTorch HIP Build Configuration

### PR DESCRIPTION
**Pull request by Jorghi12**
1) Adding missing SHARED var when using HIP_ADD_LIBRARY is invoked. FindHIP.CMake will add extra logic specific to SHARED libraries. https://github.com/ROCm-Developer-Tools/HIP/blob/master/cmake/FindHIP.cmake#L398

2) Now setting COMPILE_DEFINITIONS that were being dropped by the FindHIP.CMake toolchain.

3) ROCm transpilation and building is now done in a new directory, pytorch_amd. This will help keep development in the source directory clean.

### CODE REVIEW

**Comment by Jorghi12** [comment]
The clang3.8-rocmnightly-ubuntu16.04 is expected to succeed once a new Docker Image has been created with ROCm 1.8.2.

**Comment by Jorghi12** [comment]
@iotamudelta I think having #3 is very important in order to improve development with PyTorch ROCm. You'll now be able to make changes in the PyTorch source directory and send commits to branches. The way we had it set up before, this was not possible since the source directory became garbled with all the HIP transpilations.

**Comment by iotamudelta** [comment]
@Jorghi12 did you test this? At the very least it is missing `${}` around your variables.

**Comment by Jorghi12** [comment]
Related patch here: https://github.com/ROCm-Developer-Tools/HIP/pull/588/files

**Comment by iotamudelta** [comment]
I am still not a fan of changing it again back to `_amd`. Yes, during development you need to `git add` your changes prior to hipification but changing it back and forth is a POLA violation.

Additionally, with `hip-clang` the number of necessary hipifications will go down drastically. Last but not least - I'd prefer a caffe2-style solution in the end.

If you remove this part for the time being, I am happy to merge the rest in once it passes CI.

**Comment by Jorghi12** [comment]
@iotamudelta Let's have a chat about this in the next meeting. We're talking about the same thing.

**Comment by Jorghi12** [comment]
@iotamudelta I completely disagree, but that's fine. I'm fine with removing it from this. I can have a separate branch on my repository where I can apply the commit when I develop.

**Comment by Jorghi12** [comment]
@iotamudelta I disagree with the soundness of your reasoning, but that's fine. We can remove it from this PR. I can have a separate branch on my repository where I can apply the commit when I develop.

**Comment by Jorghi12** [comment]
@iotamudelta I completely disagree with the soundness of your reasoning, but that's fine. We can remove it from this PR. I can have a separate branch on my repository where I can apply the commit when I develop.

**Comment by Jorghi12** [comment]
And this is a related fix I've made to the HIP stack: https://github.com/ROCm-Developer-Tools/HIP/pull/588

**Comment by iotamudelta** [comment]
I've resolved the merge conflict caused by the MAX_JOBS edits upstream.

**Comment by iotamudelta** [comment]
Something was off.

@pytorchbot retest this please

**Comment by iotamudelta** [comment]
LGTM and passed CI - merging.

The debug symbols remain an issue that we need to address.

**Pull request merged**
