### PR TITLE
merge from upstream

### PR DESCRIPTION
**Pull request by iotamudelta**

### CODE REVIEW

**Comment by whchung** [comment]
@iotamudelta may i understand how often do we synchronize with pytorch upstream?

**Comment by iotamudelta** [comment]
@whchung at least weekly. why?

**Comment by whchung** [comment]
thx. just for my education

**Comment by iotamudelta** [comment]
Looks like volatile errors in Jenkins communication (macos) and out of memory (windows).
@pytorchbot retest this please

**Pull request merged**
