### PR TITLE
[ROCm] unskip test_fx tests

### PR DESCRIPTION
**Pull request by jeffdaily**

### CODE REVIEW

**Comment by jeffdaily** [comment]
The tests that this PR enables have passed in the CI log even though overall the CI is reporting a failure (not related to this PR's unskipped changes.)

**Comment by amathews-amd** [comment]
cc: @jithunnair-amd

**Review by amathews-amd — APPROVED** [review]
LGTM

**Comment by jithunnair-amd** [comment]
From http://rocmhead.amd.com:8080/job/pytorch/job/pytorch-test-2/94/consoleFull:

```
00:29:01.928   test_native_callable (__main__.TestFX) ... ok (0.020s)
00:29:02.707   test_torchbind_class_attribute_in_fx (__main__.TestFX) ... ok (0.002s)
00:29:02.707   test_torchbind_class_attribute_in_fx_tensor_arg (__main__.TestFX) ... ok (0.003s)
```

**Pull request merged**
