### PR TITLE
Added missing synchronization after GPU->GPU memory copying. Correcte…

### PR DESCRIPTION
**Pull request by kpyzhov**
…d TestCuda.test_record_stream test.

### CODE REVIEW

**Comment by kpyzhov** [comment]
The "pr/pytorch-win-ws2016-cuda9-cudnn7-py3" job failure does not seem to be caused by this change. The failing tests (**test_from_cuda_array_interface** and **test_from_cuda_array_interface_lifetime**) used to fail earlier.
For example: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-win-ws2016-cuda9-cudnn7-py3-test2/40431/console

**Comment by iotamudelta** [comment]
Streams are supposed to be in order. This is a copy from src_device == dst_device and hence no stream synchronization should be required.

**Comment by yxsamliu** [comment]
@kpyzhov could you please address @iotamudelta 's comments. Thanks.

**Pull request closed without merging**
