### PR TITLE
use hip atomicAdd

### PR DESCRIPTION
**Pull request by 7SK**

### CODE REVIEW

**Comment by ezyang** [comment]
Want to confirm that you can still merge this without my approval. The CODEOWNERS is intended for use in the upstream repo, not for this repo.

**Comment by 7SK** [comment]
@ezyang thanks

**Comment by Jorghi12** [comment]
Hey, @7SK this looks good to me. The errors on the CI appear to be unrelated to the code modifications you've provided.

**Comment by Jorghi12** [comment]
This PR will wait until ROC-1.8.2 is being used on CI. In ROC-1.8.2 is when the atomicAdd overload is added. I'd imagine it would break on rocm-nightly at the moment, which uses an older version of HIP that does not contain the atomicAdd overload.

**Comment by iotamudelta** [comment]
Note - we will include this PR once the ROCm release requires it. `hip-master` does need it.

**Comment by iotamudelta** [comment]
In #158 w/ a guard based on the ROCm version.

**Pull request closed without merging**
