### PR TITLE
[SOW MS3] Few updates to UT execution

### PR DESCRIPTION
**Pull request by pruthvistony**
- updated condition for test_out and test_out_warnings to switch to magma backend only for linalg.svdvals, default hipSolver
- Increase the tolerance for test_out_addbmm_cpu_float32

One of fixes for https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/2490

### CODE REVIEW

**Review by jeffdaily — APPROVED** [review]

**Review by alugorey — APPROVED** [review]

**Comment by jithunnair-amd** [comment]
> Increase the tolerance for test_out_addbmm_cpu_float32

Hi @pruthvistony, has this fix already been made upstream or in any other ROCm fork branches?

**Comment by pruthvistony** [comment]
> > Increase the tolerance for test_out_addbmm_cpu_float32
> 
> Hi @pruthvistony, has this fix already been made upstream or in any other ROCm fork branches?

@jithunnair-amd , no this change hasnt been part of upstream or any ROCm branches.

**Comment by jithunnair-amd** [comment]
@pruthvistony @jeffdaily As discussed offline, the `test_out_addbmm_cpu_float32` test shouldn't even be run in CI since tests with `device_type != cuda` are skipped when running tests with `test.sh`. However, since this test fails only on MI250, it does indicate that the test performs some GPU activity and exposes a GPU-specific issue with accuracy. It seems like it might be the same issue we came across in https://ontrack-internal.amd.com/browse/SWDEV-292198?focusedCommentId=7955861&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-7955861 .... 

@pruthvistony Can we file a JIRA so that we can have one of our team members look into this at some point to confirm if it is the same as the above issue?

**Comment by pruthvistony** [comment]
@jeffdaily @jithunnair-amd ,
TestCommonCPU.test_out_addbmm_cpu_float32 is having a GPU part as part of the test setting for negative condition (wrong device type) to GPU when available.
https://github.com/ROCmSoftwarePlatform/pytorch/blob/1b285690da5cd6da0393d155b565d5cc8783fe29/test/test_ops.py#L870

But the failure or error difference is happening before it reaches the GPU stage of the test case.
https://github.com/ROCmSoftwarePlatform/pytorch/blob/1b285690da5cd6da0393d155b565d5cc8783fe29/test/test_ops.py#L855

So this UT seems to be CPU related.
Failed on 2 machines both having AMD CPU and passed on 2 machines having Intel CPU.

**Comment by jithunnair-amd** [comment]
@pruthvistony This PR causes a bunch of cuda test_ops tests to fail with the error:
```
Sep 20 19:47:12     if all([TEST_WITH_ROCM, op.name == "addbmm", out.dtype == torch.float32]):
Sep 20 19:47:12 AttributeError: 'tuple' object has no attribute 'dtype'
```
Eg. http://rocmhead.amd.com:8080/job/pytorch/job/pytorch-test-1/346/consoleText

**Comment by jithunnair-amd** [comment]
jenkins retest this please

**Comment by pruthvistony** [comment]
> @pruthvistony This PR causes a bunch of cuda test_ops tests to fail on ROCm5.2 with the error:
> 
> ```
> Sep 20 19:47:12     if all([TEST_WITH_ROCM, op.name == "addbmm", out.dtype == torch.float32]):
> Sep 20 19:47:12 AttributeError: 'tuple' object has no attribute 'dtype'
> ```
> 
> Eg. http://rocmhead.amd.com:8080/job/pytorch/job/pytorch-test-1/346/consoleText

Added the fix - https://github.com/ROCmSoftwarePlatform/pytorch/pull/1109

**Pull request merged**
