### PR TITLE
[SOW MS3] Pickle and cuda_test

### PR DESCRIPTION
**Pull request by jpvillam-amd**
Fixes serialization synchronization issue 
Enables:
test_cuda test_cudnn_multiple_threads_same_device (main.TestCuda)
test_sparse test_pickle_cuda_float64 (__main__.TestSparseCUDA)

### CODE REVIEW

**Comment by okakarpa** [comment]
retest this please

**Comment by jithunnair-amd** [comment]
@jpvillam-amd Since CI is busted, can you please paste a snippet of these 2 unit tests passing in your local run and also mention the docker image you used?

**Comment by jpvillam-amd** [comment]
On `rocm/pytorch-private:rocm5.2_ubuntu20.04_py3.7_pytorch_sow_ms3`
```root@d73b3403e4f0:/home/jpvillam/tmp/pytorch# python3 test/test_sparse.py -v TestSparseCUDA.test_pickle_cuda_float64
test_pickle_cuda_float64 (__main__.TestSparseCUDA) ... ok

----------------------------------------------------------------------
Ran 1 test in 2.630s

OK
root@d73b3403e4f0:/home/jpvillam/tmp/pytorch# python3 test/test_cuda.py -v TestCuda.test_cudnn_multiple_threads_same_device
test_cudnn_multiple_threads_same_device (__main__.TestCuda) ... ok

----------------------------------------------------------------------
Ran 1 test in 34.650s

OK```

**Comment by jithunnair-amd** [comment]
retest this please

**Comment by jpvillam-amd** [comment]
> retest this please

Is that for me or for the CI? 😂

**Comment by jithunnair-amd** [comment]
> Is that for me or for the CI? 😂
For the CI

**Review by jithunnair-amd — APPROVED** [review]

**Pull request merged**
