### PR TITLE
Enable test_torch, test_dataloader, test_indexing and test_utils …

### PR DESCRIPTION
**Pull request by jithunnair-amd**
… unit tests for ROCm CI builds

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
I just hope it doesn't throw up some multi-gpu failures. The m/c I tested on has a single gpu.

**Comment by iotamudelta** [comment]
@jithunnair-amd looks like something failed

**Comment by jithunnair-amd** [comment]
@ezyang Do you have any thoughts on why these specific tests from test_torch segfault on the CI, or how to find out more info? They pass for me locally on both single- and multi-gpu machines.

**Comment by iotamudelta** [comment]
@jithunnair-amd looks like there is more to fix :-(

**Comment by jithunnair-amd** [comment]
@iotamudelta Look who passed :) I cheated a bit and took test_utils out because it was a bit trickier to figure out how to skip certain tests for it.

**Comment by iotamudelta** [comment]
@jithunnair-amd looks good - once the other targets pass I'll merge. Can you have a look at nn and sparse (I'll explain offline) next? Thanks!

**Comment by iotamudelta** [comment]
@jithunnair-amd I fear CI is stuck

@pytorchbot retest this please

**Pull request merged**
