### PR TITLE
backwards apex layer_norm cherry pick - 5.5

### PR DESCRIPTION
**Pull request by jataylo**
Cherry picks upstream updates to the Apex layer_norm port.
https://github.com/pytorch/pytorch/pull/87635
https://github.com/pytorch/pytorch/pull/87726

Needs to make into 5.5 release

Identical to 5.4 PR
https://github.com/ROCmSoftwarePlatform/pytorch/pull/1146

### CODE REVIEW

**Review by hubertlu-tw — APPROVED** [review]
LGTM

**Comment by jataylo** [comment]
Seeing many CI failures are these expected @jithunnair-amd @pruthvistony 

They are unrelated to this change.

```
http://rocmhead.amd.com:8080/job/pytorch/job/pytorch-test-distributed-1/441/consoleText
All fails give following message
Dec 07 17:39:28 AssertionError: Scalars are not equal!
Dec 07 17:39:28 
Dec 07 17:39:28 Absolute difference: 1
Dec 07 17:39:28 Relative difference: inf : Expected zero exit code but got 1 for pid: 2248035

distributed/fsdp/test_fsdp_meta failed FAILED (failures=7, skipped=7)
distributed/fsdp/test_fsdp_mixed_precision failed! FAILED (failures=39, skipped=1)
distributed/fsdp/test_fsdp_state_dict failed! FAILED (failures=63)
distributed/fsdp/test_fsdp_traversal failed! FAILED (failures=1)
```

```
http://rocmhead.amd.com:8080/job/pytorch/job/pytorch-test-1/467/console

Dec 07 18:07:06 ======================================================================
Dec 07 18:07:06 ERROR [0.002s]: test_versioned_div_tensor_inplace (jit.test_save_load_for_op_version.TestSaveLoadForOpVersion)
Dec 07 18:07:06 ----------------------------------------------------------------------
Dec 07 18:07:06     if platforms == [] or any([platform_to_conditional[platform] for platform in platforms]):
Dec 07 18:07:06 KeyError: 'dynamo'
Dec 07 18:07:06 
Dec 07 18:07:06 ----------------------------------------------------------------------

Dec 07 18:11:34 =================================== FAILURES ===================================
Dec 07 18:11:34 _______ TestCommonCUDA.test_non_standard_bool_values_argwhere_cuda_bool ________
Dec 07 18:11:34     assert_equal(
Dec 07 18:11:34   File "/opt/conda/lib/python3.8/site-packages/torch/testing/_comparison.py", line 1093, in assert_equal
Dec 07 18:11:34     raise error_metas[0].to_error(msg)
Dec 07 18:11:34 AssertionError: The values for attribute 'shape' do not match: torch.Size([2, 1]) != torch.Size([290, 1]).
Dec 07 18:11:34 - generated xml file: /var/lib/jenkins/pytorch/test/test-reports/python-pytest/test_ops/test_ops.xml -
```

```
http://rocmhead.amd.com:8080/job/pytorch/job/pytorch-test-2/468/consoleText
Dec 07 18:39:32 ======================================================================
Dec 07 18:39:32 ERROR [0.002s]: test_adamax (__main__.TestOptim)
Dec 07 18:39:32 ----------------------------------------------------------------------
Dec 07 18:39:32 KeyError: 'dynamo'
Dec 07 18:39:32 
Dec 07 18:39:32 ======================================================================
Dec 07 18:39:32 ERROR [0.001s]: test_adamw (__main__.TestOptim)
Dec 07 18:39:32 ----------------------------------------------------------------------
Dec 07 18:39:32 KeyError: 'dynamo'
Dec 07 18:39:32 
Dec 07 18:39:32 ======================================================================
Dec 07 18:39:32 ERROR [0.001s]: test_asgd (__main__.TestOptim)
Dec 07 18:39:32 ----------------------------------------------------------------------
Dec 07 18:39:32 KeyError: 'dynamo'
Dec 07 18:39:32 
Dec 07 18:39:32 ======================================================================
Dec 07 18:39:32 ERROR [0.002s]: test_nadam (__main__.TestOptim)
Dec 07 18:39:32 ----------------------------------------------------------------------
Dec 07 18:39:32 KeyError: 'dynamo'
Dec 07 18:39:32 
Dec 07 18:39:32 ======================================================================
Dec 07 18:39:32 ERROR [0.001s]: test_radam (__main__.TestOptim)
Dec 07 18:39:32 ----------------------------------------------------------------------
Dec 07 18:39:32 KeyError: 'dynamo'
Dec 07 18:39:32 
Dec 07 18:39:32 ======================================================================
Dec 07 18:39:32 ERROR [0.002s]: test_rmsprop (__main__.TestOptim)
Dec 07 18:39:32 ----------------------------------------------------------------------
Dec 07 18:39:32 KeyError: 'dynamo'
Dec 07 18:39:32 
Dec 07 18:39:32 FAILED (errors=6, skipped=1)
```

**Comment by jataylo** [comment]
Update the benchmark script we provided in upstream PR acts as expected and gives same perf improvements when building locally with this branch and PR.
https://github.com/pytorch/pytorch/pull/87635

@jeffdaily @jithunnair-amd Can we merge as fails I documented above are unrelated.

**Comment by jeffdaily** [comment]
Do we prefer squash and merge or merge?

**Comment by jataylo** [comment]
> Do we prefer squash and merge or merge?

I think squash makes most sense here. Some of the history (testing with env variables etc) is not necessarily relevant

**Pull request merged**
