### PR TITLE
Only install miopen-hip-gfx packages for ROCm5.5 onwards

### PR DESCRIPTION
**Pull request by jithunnair-amd**
Starting from ROCm5.5, miopenkernels packages are replaced by miopen-hip-gfx packages

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
@WBobby CI won't help for this PR, as it is to do with docker build step. If it looks okay, I'll merge the PR.

**Comment by WBobby** [comment]
@jithunnair-amd In this updates, we will continue the build when the "miopen-hip-gfx" packages is not available. But I think missing those packages will affect the PyTorch performance. Do we exit the build if those packages is not installed correctly?

**Comment by pruthvistony** [comment]
Needs jenkins job parameter update to rocm5.5, it is done
http://rocm-ci.amd.com/job/mainline-framework-pytorch-ci/655/

**Comment by pramenku** [comment]
Thanks @pruthvistony

**Pull request merged**
