### PR TITLE
Fix HIP_HIPCC_FLAGS

### PR DESCRIPTION
**Pull request by yxsamliu**
HIP_HIPCC_FLAGS is defined as a list with generator expression
in FindHIP.cmake. It should be treated as a list in caffe cmake
files. Also target_compile_options needs to be used since
set_target_properties does not support generator expression.

### CODE REVIEW

**Comment by iotamudelta** [comment]
@yxsamliu could you, just as with the others, please merge this into master? Thanks!

**Comment by yxsamliu** [comment]
changed base to master branch

**Comment by iotamudelta** [comment]
Only CI failure is well-known cuda6 cudnn8 one - merging. Thanks!

**Pull request merged**
