### PR TITLE
IFU-master-2021-08-05

### PR DESCRIPTION
**Pull request by hubertlu-tw**
IFU-master-2021-08-05

### CODE REVIEW

**Comment by hubertlu-tw** [comment]
@jeffdaily Could you please take a look at this diff file ([diff_THCAtomics_cuh.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/6941657/diff_THCAtomics_cuh.txt)) and confirm if the conflicts are resolved correctly?

**Comment by jeffdaily** [comment]
@hubertlu-tw I locally performed a diff between THCAtomics.cuh in upstream master and this PR branch and they are the same file --- this is the correct situation.  Thanks.

**Comment by jeffdaily** [comment]
Otherwise, waiting for CI to finish and succeed before I approve.

**Review by jithunnair-amd — APPROVED** [review]
LGTM. ROCm CI passed.

**Comment by hubertlu-tw** [comment]
A/B Testing for the current master branch ("A") and IFU-master-2021-08-05 branch ("B") by using their corresponding Apex and Torchvision commits provided in the [related_commits file](https://github.com/ROCmSoftwarePlatform/pytorch/pull/849/commits/57f9a3df4824883953e93df922f9ae2f8ac4b900). Notice that the tests have been done with [rocm/pytorch:latest-base](https://hub.docker.com/layers/rocm/pytorch/latest-base/images/sha256-806f2f5f2bbbafa09b7e4ce3254cc5bff257433d93f45a27214bb966d83d9bd8?context=repo) (rocm-4.2.0) docker image.

Please find the log files of Apex unit tests with A and B setting in the attached files.

[apex_distributed_unittests_A.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/6985552/apex_distributed_unittests_A.txt)
[apex_distributed_unittests_B.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/6985553/apex_distributed_unittests_B.txt)
[apex_unittests_A.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/6985554/apex_unittests_A.txt)
[apex_unittests_B.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/6985555/apex_unittests_B.txt)

**Comment by hubertlu-tw** [comment]
Please find the log files of Torchvision unit tests for A and B settings in the attached files.

[torchvision_unittests_A.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/6985644/torchvision_unittests_A.txt)
[torchvision_unittests_B.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/6985703/torchvision_unittests_B.txt)

**Pull request merged**
