### PR TITLE
Cherry-pick of PR #31886 from upstream

### PR DESCRIPTION
**Pull request by pruthvistony**
Support PyTorch ROCm CI on Ubuntu18.04 (#31886)

### CODE REVIEW

**Comment by pruthvistony** [comment]
@sunway513,
Please review the changes.

**Comment by pruthvistony** [comment]
Changes are built - http://rocm-ci.amd.com/view/HIP-Clang/job/compute-framework-dkms-no-npi-hipclang-ci/435/

**Comment by sunway513** [comment]
LGTM.

**Comment by pruthvistony** [comment]
Merge is done.

**Pull request merged**
