### PR TITLE
[SOW MS3] Workaround MIOPEN output tensor memory format (NDHWC) issue

### PR DESCRIPTION
**Pull request by micmelesse**
added a fix for these tests and enable them

``` 
python test_nn.py --verbose  TestNNDeviceTypeCUDA.test_conv_cudnn_ndhwc_cuda_float16
python test_nn.py --verbose  TestNNDeviceTypeCUDA.test_conv_cudnn_ndhwc_cuda_float32
```

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
retest this please

**Comment by jithunnair-amd** [comment]
http://rocmhead.amd.com:8080/job/pytorch/job/pytorch-test-1/235/consoleText
```
Aug 15 05:56:09   test_conv_cudnn_ndhwc_cuda_float16 (__main__.TestNNDeviceTypeCUDA) ... _convolution
Aug 15 05:56:09 select_conv_backend
Aug 15 05:56:09 _convolution
Aug 15 05:56:09 select_conv_backend
Aug 15 05:56:09 select_conv_backend
Aug 15 05:56:09 select_conv_backend
Aug 15 05:56:09 FAIL (0.010s)
Aug 15 05:56:09   test_conv_cudnn_ndhwc_cuda_float32 (__main__.TestNNDeviceTypeCUDA) ... _convolution
Aug 15 05:56:09 select_conv_backend
Aug 15 05:56:09 _convolution
Aug 15 05:56:09 select_conv_backend
Aug 15 05:56:09 select_conv_backend
Aug 15 05:56:09 select_conv_backend
Aug 15 05:56:09 FAIL (0.006s)
...
Aug 15 05:56:13   test_convert_conv2d_weight_memory_format_cuda (__main__.TestNNDeviceTypeCUDA) ... _convolution
Aug 15 05:56:13 select_conv_backend
Aug 15 05:56:13 miopen_convolution
Aug 15 05:56:13 FAIL (0.120s)
```

**Comment by jithunnair-amd** [comment]
@micmelesse Any progress on this PR?

**Comment by micmelesse** [comment]
@jithunnair-amd I am still working on it. Just disabling MIOPEN doesnot work. I am looking at another solution.

**Comment by micmelesse** [comment]
@jithunnair-amd Two of the tests pass. The failures donot seem related to my changes.

**Comment by micmelesse** [comment]
I will do a seperate pr for the 3 test

**Review by jithunnair-amd — APPROVED** [review]
Looks good to me, just want another review to confirm that this would be in line with how we can fix unit tests for sow ms3 branch.

**Review by jeffdaily — APPROVED** [review]

**Pull request merged**
