### PR TITLE
Merge from upstream master into our fork.

### PR DESCRIPTION
**Pull request by iotamudelta**
As upstream master is now CI validated on ROCm, make sure that our master holds the same version,

### CODE REVIEW

**Comment by iotamudelta** [comment]
@petrex I want to trigger CI to make sure our fork is (after this PR) passing all tests. For the future, I guess it should depend if it's a straightforward fast-forward merge or if there is some manual merging to be done?

**Comment by iotamudelta** [comment]
@ezyang could you have a look what is going wrong here?

**Comment by ezyang** [comment]
@iotamudelta Bad build, ignore it. We accidentally turned on tests for a period of time; they're expected to fail. This looks good to merge.

**Pull request merged**
