### PR TITLE
Suspicion is that there's an off by 1 error here.

### PR DESCRIPTION
**Pull request by Jorghi12**
The original code writer didn't correctly set the end index. This fixes that.

### CODE REVIEW

**Comment by iotamudelta** [comment]
failure on win

@pytorchbot retest this please

**Comment by jithunnair-amd** [comment]
@Jorghi12 interesting. How did this come up?

**Comment by Jorghi12** [comment]
@jithunnair-amd You'll notice that the issue occurs when replacing thread with dim(thread), transforming threads into dim(thread)s. This is due to incorrectly finding the ending index for the second kernel launch parameter <<<blocks, threads>>>. Previously, the ending index was set as len(kernel_string)-1, which would point to the "s" in threads. And so when you index the string you'll output "thread"

**Comment by iotamudelta** [comment]
Doesn't work, it seems, per CI.

**Comment by erikbrinkman** [comment]
I'm running into this bug too, and this issue actually seems to be with how it deals when the line ends. You still need the +1 on first raw because the final find and replace concatenates them first, so you need the comma, which that includes. I believe (although it's still testing) the actual fix is this commit: https://github.com/pytorch/pytorch/pull/11102/commits/d103f87d0e3716f01519c56bf5a13ae478a9780f

**Comment by iotamudelta** [comment]
@erikbrinkman could you comment on the last version of the patch? Thanks!

**Pull request merged**
