### PR TITLE
Replaced API_SOLVER to use API_SPECIAL

### PR DESCRIPTION
**Pull request by pruthvistony**

### CODE REVIEW

**Comment by pruthvistony** [comment]
CI build is progress - http://rocm-ci.amd.com/job/mainline-framework-pytorch-ci/1053/

**Comment by jithunnair-amd** [comment]
Thanks @pruthvistony. @jeffdaily, I noticed this commit was pushed without a PR: https://github.com/ROCmSoftwarePlatform/pytorch/commit/3e3c47d8204bbfce776ebd8cf43c0deb233baf93, so it didn't get tested in CI. Did it pass in your local builds?

**Comment by jeffdaily** [comment]
It was a rush job.  I wanted to prevent the backout-and-fix strategy for the recent IFU and our devops builds.  I fixed the immediate error but missed others without adequate testing.

How did the IFU merge in the first place without catching this?

**Comment by jithunnair-amd** [comment]
> It was a rush job. I wanted to prevent the backout-and-fix strategy for the recent IFU and our devops builds. I fixed the immediate error but missed others without adequate testing.
> 
> How did the IFU merge in the first place without catching this?

I think the IFU was fine because there weren't any merge conflicts, which is understandable since main is now just a copy of upstream main: https://github.com/ROCmSoftwarePlatform/pytorch/pull/1236#issuecomment-1579661458

So @pruthvistony, the bug crept in when resolving conflicts while bringing in the IFU to rocm5.7_internal_testing in https://github.com/ROCmSoftwarePlatform/pytorch/blob/006b3e67c188b7b0d27b543e9536076d6b389c85/torch/utils/hipify/cuda_to_hip_mappings.py, also via direct commit.

So, in retrospect, especially for IFUs/mass merges, we should use the PR route to get CI checks. It'll also save us some JIRAs.

**Comment by jithunnair-amd** [comment]
Build passed: http://rocmhead:8080/job/pytorch/job/pytorch-ci/738/ .. merging

**Comment by pruthvistony** [comment]
> > It was a rush job. I wanted to prevent the backout-and-fix strategy for the recent IFU and our devops builds. I fixed the immediate error but missed others without adequate testing.
> > How did the IFU merge in the first place without catching this?
> 
> I think the IFU was fine because there weren't any merge conflicts, which is understandable since main is now just a copy of upstream main: [#1236 (comment)](https://github.com/ROCmSoftwarePlatform/pytorch/pull/1236#issuecomment-1579661458)
> 
> So @pruthvistony, the bug crept in when resolving conflicts while bringing in the IFU to rocm5.7_internal_testing in https://github.com/ROCmSoftwarePlatform/pytorch/blob/006b3e67c188b7b0d27b543e9536076d6b389c85/torch/utils/hipify/cuda_to_hip_mappings.py, also via direct commit.
> 
> So, in retrospect, especially for IFUs/mass merges, we should use the PR route to get CI checks. It'll also save us some JIRAs.

Yes, PR from main to rocmx.y_internal_testing is very important now and merge conflicts should be taken care.

**Pull request merged**
