### PR TITLE
Changes to enable rccl build

### PR DESCRIPTION
**Pull request by jithunnair-amd**
Build completed successfully for me with the following command after hipification:
`PYTORCH_ROCM_ARCH=gfx900 USE_GLOO=0 USE_NCCL=1 USE_SYSTEM_NCCL=1 USE_MKLDNN=0 USE_ROCM=1 MAX_JOBS=4 KMTHINLTO=1 python setup.py install 2>&1 | tee -a $build_log`

Note that hipification logic needed slight modification so as to enable desired substitutions.

### CODE REVIEW

**Comment by iotamudelta** [comment]
Shouldn't we then also set those flags ( `USE_NCCL=1 USE_GLOO=0` etc) in `.jenkins/[pytorch,caffe2]/build.sh`?

Did you run the unit tests after that to make sure there are no failures?

**Comment by iotamudelta** [comment]
To explain, I'd like to enable QA to be able to just run `.jenkins/[pytorch,caffe2]/build.sh` and `.jenkins/[pytorch,caffe2]/test.sh` and have a working RCCL and the rest.

**Comment by jithunnair-amd** [comment]
@iotamudelta I added the env variables to the build scripts as well. However, the last build failed with the below error. I'm assuming that's expected?
```
05:28:48 CMake Error at cmake/public/LoadHIP.cmake:124 (find_package):
05:28:48   By not providing "Findrocprim.cmake" in CMAKE_MODULE_PATH this project has
05:28:48   asked CMake to find a package configuration file provided by "rocprim", but
05:28:48   CMake did not find one.
05:28:48 
05:28:48   Could not find a package configuration file provided by "rocprim" with any
05:28:48   of the following names:
05:28:48 
05:28:48     rocprimConfig.cmake
05:28:48     rocprim-config.cmake
```

**Comment by iotamudelta** [comment]
the CI unfortunately is still on hipthrust and friends, so we expect the failure from rocThrust. So this cannot be tested automatically, unfortunately.

**Comment by jithunnair-amd** [comment]
All unit tests passed with my build. I'm rebuilding with the jenkins script just to be sure.

**Comment by iotamudelta** [comment]
OK, update if that passes, then I'll merge in. Thanks!

**Comment by jithunnair-amd** [comment]
Yes, build with command:
`BUILD_ENVIRONMENT=py2-clang7-rocmdeb-ubuntu16.04 .jenkins/pytorch/build.sh`
also succeeded, and all unit tests passed with this build.

**Pull request merged**
