### PR TITLE
Remove unrecognized command line options for HIP - release/1.10.1

### PR DESCRIPTION
**Pull request by jataylo**
Remove the outdated HIP flags appended to HIP_CXX_FLAGS

This will remove the following warnings in the pytorch build log

```
[3302/5055] Building CXX object c10/hip/CMakeFiles/c10_hip.dir/HIPMiscFunctions.cpp.o
cc1plus: warning: command line option ‘-Wno-duplicate-decl-specifier’ is valid for C/ObjC but not for C++
cc1plus: warning: unrecognized command line option ‘-Wno-implicit-int-float-conversion’
cc1plus: warning: unrecognized command line option ‘-Wno-unused-command-line-argument’
cc1plus: warning: unrecognized command line option ‘-Wno-exceptions’
cc1plus: warning: unrecognized command line option ‘-Wno-inconsistent-missing-override’
cc1plus: warning: unrecognized command line option ‘-Wno-macro-redefined’
```

A corresponding change in gloo is also required to ensure these flags aren't added when compiling Caffe2 files. PR here https://github.com/ROCmSoftwarePlatform/gloo/pull/1

### CODE REVIEW

**Comment by jataylo** [comment]
jenkins retest this please

**Comment by jataylo** [comment]
jenkins retest this please

**Comment by jataylo** [comment]
@jithunnair-amd still seeing some HIP flag warnings in the CI log, let me investigate this locally before merging, could be something else in specifically the release branches that I missed
http://rocmhead:8080/job/pytorch/job/pytorch-build/777/

**Comment by jataylo** [comment]
jenkins retest this please

**Comment by jataylo** [comment]
After moving the gloo commit the unrecognized command line warnings are not seen anymore
http://rocmhead:8080/job/pytorch/job/pytorch-build/769/artifact/pytorch_log/pytorch.build.log

Compared to 
http://rocmhead:8080/job/pytorch/job/pytorch-build/769/

@jithunnair-amd @pruthvistony 
If this looks good to you I suggest we merge all the internal gloo PRs and then I can update the pinned gloo to TOT of the gloo release branches
https://github.com/ROCmSoftwarePlatform/gloo/pull/4
https://github.com/ROCmSoftwarePlatform/gloo/pull/3
https://github.com/ROCmSoftwarePlatform/gloo/pull/2
https://github.com/ROCmSoftwarePlatform/gloo/pull/1

**Review by jithunnair-amd — APPROVED** [review]

**Comment by pruthvistony** [comment]
> After moving the gloo commit the unrecognized command line warnings are not seen anymore http://rocmhead:8080/job/pytorch/job/pytorch-build/781/artifact/pytorch_log/pytorch.build.log
> 
> Compared to http://rocmhead:8080/job/pytorch/job/pytorch-build/769/
> 
> @jithunnair-amd @pruthvistony If this looks good to you I suggest we merge all the internal gloo PRs and then I can update the pinned gloo in the torch branches to TOT of the gloo release branches. [ROCmSoftwarePlatform/gloo#4](https://github.com/ROCmSoftwarePlatform/gloo/pull/4) [ROCmSoftwarePlatform/gloo#3](https://github.com/ROCmSoftwarePlatform/gloo/pull/3) [ROCmSoftwarePlatform/gloo#2](https://github.com/ROCmSoftwarePlatform/gloo/pull/2) [ROCmSoftwarePlatform/gloo#1](https://github.com/ROCmSoftwarePlatform/gloo/pull/1)

@jataylo ,
Since it is for pyTorch 1.10.1 branch, there should be corresponding gloo tag/branch 1.10.1 which is part of the submodule. The above PRs you will need to update on this commit and then update the pyTorch submodule to new commit.

**Comment by jithunnair-amd** [comment]
@jataylo Merged
https://github.com/ROCmSoftwarePlatform/gloo/pull/4
https://github.com/ROCmSoftwarePlatform/gloo/pull/3
https://github.com/ROCmSoftwarePlatform/gloo/pull/2
https://github.com/ROCmSoftwarePlatform/gloo/pull/1

**Review by jithunnair-amd — APPROVED** [review]

**Pull request merged**
