### PR TITLE
IFU_20200528

### PR DESCRIPTION
**Pull request by jithunnair-amd**

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
`caffe2-py3.6-devtoolset7-rocmrpm-centos7-test` build failed due to github connection timeout. @pytorchbot retest this please

**Comment by jithunnair-amd** [comment]
Seems like another network-related error in `caffe2-py3.6-devtoolset7-rocmrpm-centos7-test` build.
```
20:17:35 error: failed to execute compile
20:17:35 caused by: error reading compile response from server
20:17:35 caused by: Failed to read response header
20:17:35 caused by: failed to fill whole buffer
20:17:35 CMake Error at torch_hip_generated_THHTensorIndex.hip.o.cmake:174 (message):
20:17:35   Error generating file
20:17:35   /var/lib/jenkins/workspace/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/./torch_hip_generated_THHTensorIndex.hip.o
```
@pytorchbot retest this please

**Comment by jithunnair-amd** [comment]
@jeffdaily `py3.6-clang7-rocmdeb-ubuntu16.04` build passed, but `caffe2-py3.6-devtoolset7-rocmrpm-centos7-test` build is still having a rough day. This time it's an onnx compilation error:
```
22:28:57   --mypy_out: protoc-gen-mypy: Plugin failed with status code 32.
22:28:57   gmake[2]: *** [CMakeFiles/gen_onnx_proto.dir/build.make:62: onnx/onnx_ONNX_NAMESPACE_FOR_C2_CI-ml.pb.cc] Error 1
22:28:57   gmake[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/gen_onnx_proto.dir/all] Error 2
```

**Comment by jithunnair-amd** [comment]
`caffe2-py3.6-devtoolset7-rocmrpm-centos7-test` build is now fixed, however a unit test failed due to upstream changes: https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py3.6-devtoolset7-rocmrpm-centos7-trigger-test/32967/ ... pulling more commits from upstream...

**Comment by jithunnair-amd** [comment]
@jeffdaily Still seeing memory access faults for mgpu tests in `pr/py3.6-clang7-rocmdeb-ubuntu16.04` build: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-trigger/43196/

`caffe2-py3.6-devtoolset7-rocmrpm-centos7-test` build working fine now

@pytorchbot retest this please

**Comment by jeffdaily** [comment]
Memory access faults should be resolved now.  New KFD installed in CI hosts over the weekend.

**Pull request merged**
