### PR TITLE
IFU-master-2023-01-23

### PR DESCRIPTION
**Pull request by alugorey**
[conflicts.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/10483441/conflicts.txt)

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
jenkins retest this please

@alugorey CI job configurations needed an update, so I retriggered CI after the updates. Let's keep an eye on the latest run.

**Comment by jithunnair-amd** [comment]
@alugorey Also, can you please double check that you resolved all the conflicts? I see this in the last log file http://rocmhead:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-multibranch/detail/PR-1160/1/pipeline/87:
```
[2023-01-23T22:18:06.648Z] Jan 23 22:18:06 Traceback (most recent call last):

[2023-01-23T22:18:06.648Z] Jan 23 22:18:06   File "test_ops_jit.py", line 11, in <module>

[2023-01-23T22:18:06.648Z] Jan 23 22:18:06     from torch.testing._internal.common_methods_invocations import op_db

[2023-01-23T22:18:06.648Z] Jan 23 22:18:06   File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_methods_invocations.py", line 16068

[2023-01-23T22:18:06.648Z] Jan 23 22:18:06     >>>>>>> upstream/master

[2023-01-23T22:18:06.648Z] Jan 23 22:18:06     ^

[2023-01-23T22:18:06.648Z] Jan 23 22:18:06 SyntaxError: invalid syntax
```

**Comment by alugorey** [comment]
> EDIT: Looks like you missed removing the conflict marker here:
> 
> https://github.com/ROCmSoftwarePlatform/pytorch/blob/bca8ed74985e826a2b9d727111eeb30bd3cc1fc7/torch/testing/_internal/common_methods_invocations.py#L16068
> 
> @alugorey Also, can you please double check that you resolved all the conflicts? I see this in the last log file http://rocmhead:8080/blue/organizations/jenkins/pytorch%2Fpytorch-ci-multibranch/detail/PR-1160/1/pipeline/87:
> 
> ```
> [2023-01-23T22:18:06.648Z] Jan 23 22:18:06 Traceback (most recent call last):
> 
> [2023-01-23T22:18:06.648Z] Jan 23 22:18:06   File "test_ops_jit.py", line 11, in <module>
> 
> [2023-01-23T22:18:06.648Z] Jan 23 22:18:06     from torch.testing._internal.common_methods_invocations import op_db
> 
> [2023-01-23T22:18:06.648Z] Jan 23 22:18:06   File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_methods_invocations.py", line 16068
> 
> [2023-01-23T22:18:06.648Z] Jan 23 22:18:06     >>>>>>> upstream/master
> 
> [2023-01-23T22:18:06.648Z] Jan 23 22:18:06     ^
> 
> [2023-01-23T22:18:06.648Z] Jan 23 22:18:06 SyntaxError: invalid syntax
> ```

Woops! Slipped through the cracks. Fixed.

**Comment by alugorey** [comment]
jenkins retest this please

**Comment by pruthvistony** [comment]
jenkins retest this please

**Comment by pruthvistony** [comment]
jenkins retest this please

**Comment by pruthvistony** [comment]
jenkins retest this please

**Comment by pruthvistony** [comment]
jenkins retest this please

**Comment by pruthvistony** [comment]
We have a green - http://rocmhead:8080/job/pytorch/job/pytorch-ci/561/
This is awesome.

**Review by jeffdaily — APPROVED** [review]

**Comment by pruthvistony** [comment]
related_commits file is updated and committed.
Waiting CI to finish and looks good to merge.

**Review by pruthvistony — APPROVED** [review]

**Comment by pruthvistony** [comment]
Verified all the commits in related_commits file.

**Pull request merged**
