### PR TITLE
[Pytorch] enabled tests in test_nn, test_cuda and test_sparse

### PR DESCRIPTION
**Pull request by lcskrishna**

### CODE REVIEW

**Comment by iotamudelta** [comment]
I'd like to run and pass the rocm tests a few times to make sure we are not having any flaky issues. :-)

**Comment by lcskrishna** [comment]
Pytorch tests passed for the first time. Retesting it.
@pytorchbot retest this please

**Comment by lcskrishna** [comment]
pytorch rocm tests passed again. retesting it again to verify if there is any flaky test.
@pytorchbot  retest this please.

**Comment by lcskrishna** [comment]
Passed all tests. Just wanted to confirm that there are no flaky tests.
@pytorchbot  retest this please.

**Pull request merged**
