### PR TITLE
Reenable test_sparse unit tests that are now passing in ROCm

### PR DESCRIPTION
**Pull request by jithunnair-amd**

### CODE REVIEW

**Comment by iotamudelta** [comment]
Running test_sparse ...
test_add_dense_sparse_mismatch (__main__.TestCudaSparse) ... Traceback (most recent call last):
  File "test/run_test.py", line 391, in <module>
    main()
  File "test/run_test.py", line 383, in main
    raise RuntimeError(message)
RuntimeError: test_sparse failed! Received signal: SIGSEGV

**Comment by jithunnair-amd** [comment]
At this point, does the CI have the latest debs for the following ROCm libs? Trying to see what's different in my local environment vs CI environment. Here's what I had in my local env where this passed:
```
hcc                         1.2.18272
hip_hcc                     1.5.18354
rocsparse                   0.1.2.114
hipsparse                   0.1.2.55
```

**Comment by iotamudelta** [comment]
Yes, it does.

**Pull request merged**
