### PR TITLE
rocm_3.5_internal_testing IFU_20200601

### PR DESCRIPTION
**Pull request by jithunnair-amd**

### CODE REVIEW

**Comment by jeffdaily** [comment]
```
22:40:16 [ 81%] Building HIPCC object caffe2/CMakeFiles/torch_hip.dir/__/aten/src/ATen/native/hip/torch_hip_generated_SoftMax.hip.o
22:40:18 /var/lib/jenkins/workspace/aten/src/ATen/native/hip/SoftMax.hip:131:2: error: unterminated conditional directive
22:40:18 #if defined(__HIP_PLATFORM_HCC__) && HIP_VERSION < 305
22:40:18  ^
22:40:18 1 error generated.
```
Looks like merge failed.

**Comment by sunway513** [comment]
@jithunnair-amd  can you review the CI failures?

**Comment by jithunnair-amd** [comment]
@jeffdaily The centos build failed with the same "random" `error reading compile response from server` error. However, we're seeing a return of the `beefdead` memory access faults in the ubuntu test builds. Are the CI machines for ROCm fork CI different than those for upstream?

**Comment by jeffdaily** [comment]
CI machines for ROCm fork are same machines for upstream ROCm CI.

**Comment by jithunnair-amd** [comment]
Okay, that doesn't bode well. I'm going to rerun CI to see if these issues persist. Here are the links to the builds for this run:
Centos: https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py3.6-devtoolset7-rocmrpm-centos7-trigger-test/33353/
Ubuntu: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-trigger/43536/

@pytorchbot retest this please

**Comment by sunway513** [comment]
@jithunnair-amd , as suggested by @jeffdaily , we can abandon this PR and focus on creating the rocm3.6_internal_testing branch. 
Thanks a lot for the efforts here!

**Comment by jithunnair-amd** [comment]
Okay, created a new branch from `upstream` branch here: https://github.com/ROCmSoftwarePlatform/pytorch/tree/rocm3.6_internal_testing

**Pull request closed without merging**
