### PR TITLE
Add CI=1 environment variable as part of test.sh

### PR DESCRIPTION
**Pull request by pruthvistony**

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
@jeffdaily Would you know if there's an explicit place in upstream source code where CI=1 is defined?

**Comment by jeffdaily** [comment]
https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables

GitHub Actions automatically defines this.

**Comment by jithunnair-amd** [comment]
> https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
> 
> GitHub Actions automatically defines this.

@pruthvistony That's what I mentioned in the morning as the second possibility :) I am okay with the above change.

**Review by jithunnair-amd — APPROVED** [review]

**Comment by pruthvistony** [comment]
> > https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
> > GitHub Actions automatically defines this.
> 
> @pruthvistony That's what I mentioned in the morning as the second possibility :) I am okay with the above change.

I will cherry-pick this change into rocm5.5_internal_testing branch and enable custom test handlers.

**Pull request merged**
