### PR TITLE
IFU-master-2022-04-26

### PR DESCRIPTION
**Pull request by rraminen**
Conflict file is attached.
[conflicts.diff.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/8566422/conflicts.diff.txt)

### CODE REVIEW

**Comment by rraminen** [comment]
test pytorch/apex/torchvision please

**Comment by rraminen** [comment]
The below test fails in unit tests suite 1

> test_nadam (__main__.TestOptim)

The below tests fail in unit tests suite 2

> test_conv1d_same_padding_cuda_complex64 (__main__.TestNNDeviceTypeCUDA)
> test_nadam (__main__.TestOptim)

The below tests fail in distributed tests

> test_pure_fp16_cpu_offload_CPUOffload(offload_params=True) (__main__.TestPureFP16)
> test_data_parallel_module_kwargs_only_cuda_float16 (__main__.TestDataParallelDeviceTypeCUDA)

Issue filed regarding test_nadam (__main__.TestOptim) test: https://ontrack-internal.amd.com/browse/SWDEV-311125

These failures are reported by triage team.

The below two tests are skipped in upstream CI:
> test_nadam (__main__.TestOptim)
> test_pure_fp16_cpu_offload_CPUOffload(offload_params=True) (__main__.TestPureFP16)

Attached are the logs: 
[pytorch.test1_IFU-master-2022-04-26.log](https://github.com/ROCmSoftwarePlatform/pytorch/files/8642630/pytorch.test1_IFU-master-2022-04-26.log)
[pytorch.test2_IFU-master-2022-04-26.log](https://github.com/ROCmSoftwarePlatform/pytorch/files/8642631/pytorch.test2_IFU-master-2022-04-26.log)
[pytorch.test_distributed_IFU-master-2022-04-26.log](https://github.com/ROCmSoftwarePlatform/pytorch/files/8642633/pytorch.test_distributed_IFU-master-2022-04-26.log)

**Comment by rraminen** [comment]
http://rocmhead.amd.com:8080/job/pytorch/job/pytorch-ci/56/

Apex unit tests look good
[apex.test_IFU-master-2022-04-26.log](https://github.com/ROCmSoftwarePlatform/pytorch/files/8642657/apex.test_IFU-master-2022-04-26.log)

Torchvision unit tests look good
[Uploading torchvision.test_IFU-master-2022-04-26.log…]()

**Comment by pruthvistony** [comment]
> The below test fails in unit tests suite 1
> 
> > test_nadam (**main**.TestOptim)
> 
> The below tests fail in unit tests suite 2
> 
> > test_conv1d_same_padding_cuda_complex64 (**main**.TestNNDeviceTypeCUDA)
> > test_nadam (**main**.TestOptim)
> 
> The below tests fail in distributed tests
> 
> > test_pure_fp16_cpu_offload_CPUOffload(offload_params=True) (**main**.TestPureFP16)
> > test_data_parallel_module_kwargs_only_cuda_float16 (**main**.TestDataParallelDeviceTypeCUDA)
> 
> Issue filed regarding test_nadam (**main**.TestOptim) test: https://ontrack-internal.amd.com/browse/SWDEV-311125
> 
> These failures are reported by triage team.
> 
> The below two tests are skipped in upstream CI:
> 
> > test_nadam (**main**.TestOptim)
> > test_pure_fp16_cpu_offload_CPUOffload(offload_params=True) (**main**.TestPureFP16)
> 
> Attached are the logs: [pytorch.test1_IFU-master-2022-04-26.log](https://github.com/ROCmSoftwarePlatform/pytorch/files/8642630/pytorch.test1_IFU-master-2022-04-26.log) [pytorch.test2_IFU-master-2022-04-26.log](https://github.com/ROCmSoftwarePlatform/pytorch/files/8642631/pytorch.test2_IFU-master-2022-04-26.log) [pytorch.test_distributed_IFU-master-2022-04-26.log](https://github.com/ROCmSoftwarePlatform/pytorch/files/8642633/pytorch.test_distributed_IFU-master-2022-04-26.log)

These failures have been seen in the 48 hrs upstream tests done by SDT team. Tickets have been raised and they are been debugged. Regarding skipping of these tests dont want to do any code skip changes now and hoping few of these will be fixed before 5.3 release.

**Review by pruthvistony — APPROVED** [review]

**Comment by KyleCZH** [comment]
test pytorch please

**Pull request merged**
