### PR TITLE
[DO_NOT_MERGE] testing cherry-picks into rocm6.0_internal_testing

### PR DESCRIPTION
**Pull request by BLOrange-AMD**

### CODE REVIEW

**Comment by BLOrange-AMD** [comment]
Testing if standalone apex/torchvision CI run without pytorch unit testing
retest apex/torchvision please

**Comment by jithunnair-amd** [comment]
@jeffdaily We're exploring process improvements in how we update the internal_testing branches after every IFU to master branch. So far, we've been manually cherry-picking commits from the "older" internal_testing branch to the "newer" one. However, filing a PR (and merging it with the ["Rebase and merge" option](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#rebase-and-merge-your-commits)) should achieve *almost* the same effect. The only caveat is it would also bring in some unnecessary merge commits such as https://github.com/ROCmSoftwarePlatform/pytorch/pull/1150/commits/4edf10eab424db79215744f27ef22fbd5ae2946f, which a manual cherry-pick process wouldn't. 

Any thoughts on whether this process is better or worse?

**Comment by jeffdaily** [comment]
The IFU process tends to bury our cherry-picks when we apply them without using PRs.  I think PRs, properly labeled, would make it easy to see what we did to a testing branch.  I'm in favor of PRs for record-keeping purposes.

**Comment by pruthvistony** [comment]
I also vote for PR. This PR gives all the differences between internal branch and upstream (may be few missed which are already in master).

**Comment by BLOrange-AMD** [comment]
retest pytorch/apex/torchvision please

**Comment by BLOrange-AMD** [comment]
retest torch please

**Comment by BLOrange-AMD** [comment]
retest pytorch please

**Comment by jithunnair-amd** [comment]
retest pytorch please

**Comment by jithunnair-amd** [comment]
Closing as @pruthvistony is working on a separate effort to update rocm6.0_internal_testing branch.

**Pull request closed without merging**
