### PR TITLE
Rocm5.1 internal testing navi21 fix

### PR DESCRIPTION
**Pull request by micmelesse**
This pr imports the fix for navi that are currently being upstreamed into pytorch. It also cherry picks some upstream commits that are need to make this work.

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
Retriggering pytorch CI since the last run didn't run PyTorch unit tests

test pytorch please

**Comment by micmelesse** [comment]
@jithunnair-amd Can you merge the pr if it is fine or the failures something we should look at?

**Comment by jithunnair-amd** [comment]
test pytorch please

**Comment by pruthvistony** [comment]
test pytorch please

**Comment by jithunnair-amd** [comment]
Email from QA (Pramendra Kumar) on 2/21/2022:
```
Hi Michael,

Please merge the change. Issue is fixed.  Comment in the ticket as well.

Thanks,
Pramendra
```

**Pull request merged**
