### PR TITLE
IFU-master-2023-03-01

### PR DESCRIPTION
**Pull request by jithunnair-amd**
[conflicts.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/10865845/conflicts.txt)

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
jenkins retest this please

**Comment by jithunnair-amd** [comment]
jenkins retest this please

**Comment by jithunnair-amd** [comment]
jenkins retest this please

**Comment by jithunnair-amd** [comment]
jenkins retest this please

**Comment by jithunnair-amd** [comment]
http://rocmhead:8080/job/pytorch/job/pytorch-ci/625/: 
- Used .ci scripts instead of .jenkins. 
- distributed-1 failed with timeout: bad node ixt-hq-15? 
- test-1 failed with test_ops and test_cuda failures:
> ERROR [0.008s]: test_torch_manual_seed_seeds_cuda_devices (__main__.TestCuda)

**Comment by jithunnair-amd** [comment]
jenkins retest this please

**Comment by jithunnair-amd** [comment]
http://rocmhead:8080/job/pytorch/job/pytorch-ci/626/:

* distributed-2 failed with timeout for distributed/algorithms/quantization/test_quantization.py: bad node ixt-hq-15?
* test-1 failed with timeout for test_decomp: bad node rocm-framework-test-0.amd.com?
* test-2 failed with profiler/test_memory_profiler:
> FAIL [0.156s]: test_memory_timeline (__main__.TestMemoryProfilerE2E)

**Comment by jithunnair-amd** [comment]
jenkins retest this please (with rocAutomation scripts updated to `pip install requirements-ci.txt`)

**Comment by jithunnair-amd** [comment]
jenkins retest this please (with rocAutomation scripts updated to pip install requirements-ci.txt)

**Comment by jithunnair-amd** [comment]
arrgh: http://rocmhead:8080/job/pytorch/job/pytorch-ci/641/:

* test-1 failed with timeout due to 5hrs spent doing just `git fetch` *rolling eyes*
```
03:20:28  > git fetch --no-tags --force --progress -- https://github.com/ROCmSoftwarePlatform/pytorch +refs/heads/master:refs/remotes/origin/master +refs/pull/1194/*:refs/remotes/origin/pr/1194/* # timeout=600
08:19:48  > git config remote.origin.url https://github.com/ROCmSoftwarePlatform/pytorch # timeout=600
```
* test-2 failed with profiler/test_memory_profiler. Should be fixed via cherry-pick: https://github.com/ROCmSoftwarePlatform/pytorch/pull/1194/commits/b17af816ad49344463ebab6fde43889be196b67a
* distributed-2 failed with timeout for `distributed/test_distributed_spawn.py`: bad node ixt-sjc2-47?

**Comment by jithunnair-amd** [comment]
http://rocmhead:8080/job/pytorch/job/pytorch-ci-multibranch/job/PR-1194/1/display/redirect:

* test-1: `test_torch_manual_seed_seeds_cuda_devices (__main__.TestCuda)` failure seen before. However, since test itself didn't fail on local reproduction attempts, I cannot just skip this test. Leaving it unskipped to be investigated via issue https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/3869
* test-2: `test_ops_fwd_gradients.py::TestFwdGradientsCUDA::test_forward_mode_AD_linalg_det_singular_cuda_complex128` failed with:
```
Mar 18 02:57:39 torch.autograd.gradcheck.GradcheckError: While considering the imaginary part of complex inputs only, Jacobian computed with forward mode mismatch for output 0 with respect to input 0,
Mar 18 02:57:39 numerical:tensor([0.0969+0.3037j], device='cuda:0', dtype=torch.complex128)
Mar 18 02:57:39 analytical:tensor([0.+0.j], device='cuda:0', dtype=torch.complex128,
Mar 18 02:57:39        grad_fn=<CopyBackwards>)
```
* distributed-1 and -2 passed (hallelujah!)

**Comment by jithunnair-amd** [comment]
jenkins notest pytorch
retest apex/torchvision/deepspeed please

**Comment by jithunnair-amd** [comment]
jenkins notest pytorch
retest apex/torchvision/deepspeed please

**Comment by jithunnair-amd** [comment]
http://rocmhead:8080/job/pytorch/job/pytorch-ci/653/
4 torchvision tests failed:
```
FAILED test/test_transforms.py::test_functional_deprecation_warning[True-from torchvision.transforms import functional_pil]
FAILED test/test_transforms.py::test_functional_deprecation_warning[True-from torchvision.transforms import functional_tensor]
FAILED test/test_transforms.py::test_functional_deprecation_warning[True-from torchvision.transforms.functional_tensor import resize]
FAILED test/test_transforms.py::test_functional_deprecation_warning[True-from torchvision.transforms.functional_pil import resize]
```
These tests are skipped upstream though eg. https://ossci-raw-job-status.s3.amazonaws.com/log/pytorch/vision/12126909908
```
2023-03-20T11:50:16.2076760Z test/test_transforms.py::test_functional_deprecation_warning[True-from torchvision.transforms import functional_pil] [33mSKIPPED[0m[33m [ 17%][0m
2023-03-20T11:50:16.2083026Z test/test_transforms.py::test_functional_deprecation_warning[True-from torchvision.transforms import functional_tensor] [33mSKIPPED[0m[33m [ 17%][0m
2023-03-20T11:50:16.2090372Z test/test_transforms.py::test_functional_deprecation_warning[True-from torchvision.transforms.functional_tensor import resize] [33mSKIPPED[0m[33m [ 17%][0m
2023-03-20T11:50:16.2095966Z test/test_transforms.py::test_functional_deprecation_warning[True-from torchvision.transforms.functional_pil import resize] [33mSKIPPED[0m[33m [ 17%][0m
```

Need to figure out why these tests are not being skipped in our runs, but doesn't seem to be a blocker for IFU.

**Comment by lcskrishna** [comment]
@jithunnair-amd In the latest release of torchvision, there is an introduction of new transformsv2 API and few of the old APIs like torchvision.transforms.functional_pil are getting deprecated and will become private from 0.17. 
Probably these tests are coming from those. Will look into the code and see why they are not being skipped for us.

**Comment by jithunnair-amd** [comment]
> @jithunnair-amd In the latest release of torchvision, there is an introduction of new transformsv2 API and few of the old APIs like torchvision.transforms.functional_pil are getting deprecated and will become private from 0.17. Probably these tests are coming from those. Will look into the code and see why they are not being skipped for us.

https://github.com/pytorch/vision/pull/7501

**Pull request merged**
