### PR TITLE
IFU_rocm5.0-internal-testing_2021-11-09

### PR DESCRIPTION
**Pull request by zstreet87**
[conflicts.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/7505675/conflicts.txt)

Only a few actual changes but these couple of changes occur in multiple files.  These changes are mainly defining new functions that allow for less dependencies on legacy code found in THC.

### CODE REVIEW

**Comment by jeffdaily** [comment]
Looks like there were a lot of conflicts surrounding warp size.  We are still working through the reviews upstream.  Since this branch was the only one to contain dynamic warp size query, we should ask QA to rerun their tests.

**Comment by zstreet87** [comment]
Investigating the Jenkins and local build errors pointed to the Macros.h merge in the conflicts.txt file.  The upstream macro in Macros.h seemed to generate a "__assert_fail" function and there is already a function with the same name in rocm.  So duplicate definition errors were produced once the generated hip files were produced.  I did produce a build error locally that I couldn't find in the Jenkins log so had to see if Jenkins will actually complain

**Comment by zstreet87** [comment]
New build errors in Jenkins build...
make[2]: *** [caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/native/mkldnn/Pooling.cpp.o] Error 1
make[1]: *** [caffe2/CMakeFiles/torch_cpu.dir/all] Error 2

I did not see these errors locally but will test locally again tomorrow.

**Comment by zstreet87** [comment]
Able to build locally with the following changes (all files are in aten/src/ATen/native/cuda/):

UnfoldBackwardKernel.cu --- revert back to HEAD
ScatterGatherKernel.cu --- revert back to HEAD
LinearAlgebra.cu --- revert back to HEAD
FunctionOfAMatrixUtilsKernel.cu --- revert back to HEAD

All these functions would throw errors when trying upstream's function call (or slight modification to this):
_launch_kernel<num_threads(), thread_work_size()>(iter.numel(), loop);


Embedding.cu --- use upstream but had to add "warp_size = at::cuda::warp_size();
Indexing.cu --- use upstream but had to add "warp_size = at::cuda::warp_size();

These two concern me because the upstream didn't have the line I added but the compilation error with only the upstream code was warp_size is undefined, which is required just below where the upstream is in conflict with HEAD.  This explicit assignment of warp_size was in HEAD so I added this which produced a build with no errors.

**Comment by pruthvistony** [comment]
@zstreet87, 
Are there any place where it was needed to add ROCM_VERSION specific checks (>=40301)? 
I agree with Jeff, can a docker image along with this PR can be shared with QA to run the tests on all the archs.

**Comment by zstreet87** [comment]
@pruthvistony If you look at the conflicts.txt file, the last conflict is in c10/macros/Macros.h  In this file, upstream has the following line 

#if defined(__ANDROID__) || defined(__APPLE__) || defined(__XROS__) || \
        (defined(USE_ROCM) && ROCM_VERSION < 40100)

With this macro instead of what is in this repository's HEAD, I had the error I initially reported in this PR 
https://github.com/ROCmSoftwarePlatform/pytorch/pull/874#issuecomment-964632227

**Pull request closed without merging**
