### PR TITLE
Enable unit tests for ROCm builds in CI …

### PR DESCRIPTION
**Pull request by jithunnair-amd**
…and exclude the ones that aren't working currently

### CODE REVIEW

**Comment by iotamudelta** [comment]
@jithunnair-amd a lot of crashing bots ;-)

**Comment by jithunnair-amd** [comment]
Yup. Trying to see if it's a result of my changes or not.

**Comment by iotamudelta** [comment]
@jithunnair-amd the test fails on loading the dynlib as it depends on libc++. This should either be addressed by other targets (caffe2 tests) or needs to be fixed on the CI node if libc++1-dev is not installed (you'll also need libc++abi1-dev). Probably the later.

**Comment by iotamudelta** [comment]
@pytorchbot retest this please

Looked like a network issue.

**Comment by iotamudelta** [comment]
Just disable for now, or?

```
15:27:11 test_requires_grad_factory (__main__.TestAutograd) ... python: symbol lookup error: /usr/local/lib/python2.7/dist-packages/torch/lib/libcaffe2_hip.so: undefined symbol: hiprngMakeMTGP32Constants
15:27:11 Traceback (most recent call last):
15:27:11   File "test/run_test.py", line 361, in <module>
15:27:11     main()
15:27:11   File "test/run_test.py", line 353, in main
15:27:11     raise RuntimeError(message)
15:27:11 RuntimeError: test_autograd failed!
```

**Comment by jithunnair-amd** [comment]
I'll disable the test

**Comment by jithunnair-amd** [comment]
The errors in test_autograd are all due to "LAPACK not found". There are other tests though (eg. test_gesv) that skipped due to the same reason. Any hunches? @ezyang @iotamudelta

**Comment by iotamudelta** [comment]
`test_inputbuffer_add_multigpu` is the next to fail - I think it is fair to just blanket disable multi GPU for now. We are not yet there and will track with #31

**Comment by iotamudelta** [comment]
`test_type_conversions` next issue

**Comment by jithunnair-amd** [comment]
I'm going to scale back my ambitions and restrict the unit test groups to just test_autograd for now, so that this PR can go in and we can at least have "a" baseline of unit tests for the CI. Otherwise this game of whackamole could go all week long. I'm also setting up a PyTorch build on a multi-GPU machine without Anaconda python to replicate the CI environment as much as possible. Hopefully, that will throw up all the tests that didn't fail in my local m/c but failed here on the CI.

**Comment by iotamudelta** [comment]
@ezyang we are about to merge this - can you have a look what would need to be done from your perspective to get this also working on the upstream CI? Thanks!

**Comment by jithunnair-amd** [comment]
@ezyang  The current failure is because the `.jenkins/pytorch/build.sh` doesn't call the steps after `python setup.py install` that it calls for non-ROCm builds. One of those steps creates the `build/bin` directory that the `test_aten()` method in `.jenkins/pytorch/test.sh` is looking for. I think someone from the FB side should refactor the `.jenkins/pytorch/build.sh` script to ensure that it runs the rest of the steps for ROCm builds as well.

**Comment by jithunnair-amd** [comment]
W00t! rocm build passed with unit tests! macos build failed for random reason. @pytorchbot retest this please.

**Comment by iotamudelta** [comment]
@jithunnair-amd I merged from master - please check. Also: if this passes CI, do you think it's ready for integration? If so, please have @ezyang review this. Thanks!

**Comment by jithunnair-amd** [comment]
Merge seems harmless. I think it is ready for integration.

**Comment by iotamudelta** [comment]
@jithunnair-amd failing again. can you check? thanks!

**Comment by jithunnair-amd** [comment]
@ezyang  Can you please take a look? I tried a fix for the 'lapack not found' issue by using `repr(e)` instead of `e.args[0]`, but that didn't seem to work. It seems like the error text matches perfectly, so I'm not sure what's the issue here.

**Comment by iotamudelta** [comment]
@jithunnair-amd you'll need to merge again, sorry.

**Comment by iotamudelta** [comment]
@pytorchbot retest this please

shaky CI is shaky again

**Pull request merged**
