### PR TITLE
Added ROCm support for cuda lazy init check

### PR DESCRIPTION
**Pull request by jataylo**
Replaces CUDA_VISIBLE_DEVICES with HIP_VISIBLE_DEVICES for ROCm.

### CODE REVIEW

**Comment by jataylo** [comment]
retest pytorch please

**Comment by jataylo** [comment]
retest pytorch please

**Comment by jataylo** [comment]
retest pytorch please

**Comment by jataylo** [comment]
retest pytorch please

**Comment by jataylo** [comment]
This test now passes with the CI.
13:46:19 Aug 30 12:46:19   test_lazy_init (__main__.TestCuda)
13:46:22 Aug 30 12:46:22 Validate that no CUDA calls are made during `import torch` call ... ok (2.623s)

I will rebase to clean the history then open up the PR for review.

**Comment by jataylo** [comment]
Passes in latest CI log.

http://rocmhead.amd.com:8080/job/pytorch/job/pytorch-test-2/286/consoleFull
15:43:22 Aug 30 14:43:22   test_lazy_init (__main__.TestCuda)
15:43:24 Aug 30 14:43:24 Validate that no CUDA calls are made during `import torch` call ... ok (2.429s)

Opening for review

**Review by jithunnair-amd — APPROVED** [review]
LGTM

**Pull request merged**
