### PR TITLE
Add bfloat16 datatype for nccl calls

### PR DESCRIPTION
**Pull request by jithunnair-amd**
Short and sweet! Needs the new rccl changes to recognize the `ncclBfloat16` datatype

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
Tested a simple model with dataparallel and distributed_dataparallel.

**Comment by iotamudelta** [comment]
LGTM, BUT: since we are waiting for the RCCL release with this support, I don't want to merge yet as to not break our CI verification.

**Comment by jithunnair-amd** [comment]
Agree completely.

**Comment by jithunnair-amd** [comment]
Filed a new PR directly upstream: https://github.com/pytorch/pytorch/pull/38515, so closing this PR.

**Pull request closed without merging**
