### PR TITLE
IFU-master-2022-11-22

### PR DESCRIPTION
**Pull request by BLOrange-AMD**

### CODE REVIEW

**Comment by BLOrange-AMD** [comment]
Add conflicts.txt.
[conflicts.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/10071781/conflicts.txt)

**Comment by BLOrange-AMD** [comment]
jenkins retest this please

**Comment by BLOrange-AMD** [comment]
test apex/torchvision please

**Comment by BLOrange-AMD** [comment]
retest pytorch/apex/torchvision please

**Comment by BLOrange-AMD** [comment]
retest pytorch/apex/torchvision please

**Comment by BLOrange-AMD** [comment]
retest pytorch/apex/torchvision please

**Comment by BLOrange-AMD** [comment]
retest pytorch/apex/torchvision please

**Comment by jithunnair-amd** [comment]
CI job shows all pytorch build and test jobs passed: http://rocmhead.amd.com:8080/job/pytorch/job/pytorch-ci/488/
(CI job failed at apex build stage due to node being abruptly rebooted). We already tested apex and torchvision in http://rocmhead.amd.com:8080/job/pytorch/job/pytorch-ci/487/.
@BLOrange-AMD also tested torchdata, torchaudio and torchtext locally to make sure the related_commits file works.

**Review by pruthvistony — APPROVED** [review]

**Pull request merged**
