### PR TITLE
[SOW MS3] Enable/fix unit tests test_stream_args and test_event_args

### PR DESCRIPTION
**Pull request by alugorey**
This PR fixes the following tests
test_jit test_stream_args (jit.test_cuda.TestCUDA)
test_jit test_event_args (jit.test_cuda.TestCUDA)

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
retest this please

**Comment by alugorey** [comment]
> retest this please

Done. Still passes

**Comment by okakarpa** [comment]
retest this please

**Comment by manitera** [comment]
retest this please

**Comment by okakarpa** [comment]
retest this please

**Comment by jithunnair-amd** [comment]
@alugorey CI is still busted. :( Would you mind posting a snippet of the passing unit tests from your local run logs? Please mention the docker image you used.

**Comment by alugorey** [comment]
Docker Container used: rocm/pytorch-private:rocm5.2_ubuntu20.04_py3.7_pytorch_sow_ms3
Logs
```
root@69f964c62a59:/home/pytorch# PYTORCH_TEST_WITH_ROCM=1 python test/test_jit.py TestCUDA.test_stream_args
.
----------------------------------------------------------------------
Ran 1 test in 0.963s

OK
root@69f964c62a59:/home/pytorch# PYTORCH_TEST_WITH_ROCM=1 python test/test_jit.py TestCUDA.test_event_args.
----------------------------------------------------------------------
Ran 1 test in 0.957s

OK
'''

**Review by jithunnair-amd — APPROVED** [review]
LGTM. CI is busted, so using local run log results as acceptance criteria.

**Pull request merged**
