### PR TITLE
Add 'extern "C"' to getRNGState/setRNGState function definitions …

### PR DESCRIPTION
**Pull request by jithunnair-amd**
…so that hcc outputs demangled symbols

### CODE REVIEW

**Comment by iotamudelta** [comment]
the fix is of course pretty fragile (for white space). did you file a hip/hcc issue yet? but yeah, LGTM (even though it worries me)

**Comment by jithunnair-amd** [comment]
Filed a HIP issue: https://github.com/ROCm-Developer-Tools/HIP/issues/630
Should I file an HCC issue instead, as Jack suggested?

**Comment by iotamudelta** [comment]
Sure. Link them both. I don't care where it gets fixed, it needs to get fixed.

**Comment by jithunnair-amd** [comment]
https://github.com/RadeonOpenCompute/hcc/issues/839

**Pull request merged**
