### PR TITLE
[SOW MS3] Correcting the condition for addbmm cpu test

### PR DESCRIPTION
**Pull request by pruthvistony**

### CODE REVIEW

**Comment by pruthvistony** [comment]
Fixes the break caused by PR - https://github.com/ROCmSoftwarePlatform/pytorch/pull/1100
and failures in -  http://rocmhead.amd.com:8080/job/pytorch/job/pytorch-test-1/346/consoleText

**Review by jithunnair-amd — APPROVED** [review]
@pruthvistony LGTM, but let's wait for a proper CI run (re-run in case it hits bad CI nodes) with a successful build and test_ops run (without the errors related to this PR at least) before merging this.

**Comment by pruthvistony** [comment]
jenkins retest this please

**Comment by pruthvistony** [comment]
jenkins retest this please

**Comment by pruthvistony** [comment]
jenkins retest this please

**Comment by pruthvistony** [comment]
jenkins retest this please

**Comment by pruthvistony** [comment]
jenkins retest this please

**Comment by pruthvistony** [comment]
jenkins retest this please

**Comment by pruthvistony** [comment]
test_out_topk_cuda_float32 (__main__.TestCommonCUDA) ... ok (0.216s)
test_out_symeig_cuda_float32 (__main__.TestCommonCUDA) ... ok (0.150s)
test_out_svd_cuda_float32 (__main__.TestCommonCUDA) ... ok (5.935s)
...
and other failing tests with error - 'tuple' object has no attribute 'dtype' have passed.

**Pull request merged**
