### PR TITLE
IFU-master-2022-03-18

### PR DESCRIPTION
**Pull request by hubertlu-tw**
No conflicts.

### CODE REVIEW

**Comment by hubertlu-tw** [comment]
test pytorch/apex/torchvision please

**Comment by hubertlu-tw** [comment]
test pytorch please

**Comment by hubertlu-tw** [comment]
Since the magma fix for OOM and memory leak has not added to rocm/pytorch:latest (the docker CI checks used), I tested the build and unit tests locally. In addition, 
Currently, `.jenkins/pytorch/test.sh` triggered the unit tests with the following lines:
`/opt/conda/bin/python3.7 test/run_test.py --exclude-jit-executor --exclude-distributed-tests --verbose`. It means we need to run the distributed unit tests separately by the following line:
`test/run_test.py --distributed-tests --verbose`

The tip of the current master branch in ROCm PyTorch is [4a1785](https://github.com/ROCmSoftwarePlatform/pytorch/commit/4a1785ce35afe7d2cd8d40cfd1401b1d4dca8f2d). Therefore, I used it to do A/B testing with the current IFU PR.

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>


<div style='direction:ltr'>



  | PyTorch   Build | PyTorch unit   tests   (--exclude-jit-executor   --exclude-distributed-tests) | PyTorch   distributed unit tests
-- | -- | -- | --
[IFU-master-2022-03-06](https://github.com/ROCmSoftwarePlatform/pytorch/pull/918) |[build_log_IFU-master-2022-03-06.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/8326884/build_log_IFU-master-2022-03-06.txt)   | [PT_unittests_log_IFU-master-2022-03-06.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/8326886/PT_unittests_log_IFU-master-2022-03-06.txt)  |  [PT_unittests_log_IFU-master-2022-03-06_distributed.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/8326888/PT_unittests_log_IFU-master-2022-03-06_distributed.txt)
[IFU-master-2022-03-18](https://github.com/ROCmSoftwarePlatform/pytorch/pull/921) | [build_log_IFU-master-2022-03-18.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/8326889/build_log_IFU-master-2022-03-18.txt)  | [PT_unittests_log_IFU-master-2022-03-18.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/8326892/PT_unittests_log_IFU-master-2022-03-18.txt)  |  [PT_unittests_log_IFU-master-2022-03-18_distributed.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/8326894/PT_unittests_log_IFU-master-2022-03-18_distributed.txt)



</div>


</body>

</html>

**Comment by hubertlu-tw** [comment]
Updated log files:
[IFU-master-2022-03-06.zip](https://github.com/ROCmSoftwarePlatform/pytorch/files/8353850/IFU-master-2022-03-06.zip)
[IFU-master-2022-03-18.zip](https://github.com/ROCmSoftwarePlatform/pytorch/files/8353851/IFU-master-2022-03-18.zip)

**Comment by KyleCZH** [comment]
test pytorch please

**Comment by KyleCZH** [comment]
test pytorch please

**Comment by KyleCZH** [comment]
test pytorch please
latest pytorch-ci build should have continue-through-error flag

**Comment by KyleCZH** [comment]
test pytorch please

**Comment by jithunnair-amd** [comment]
CI runs show some unit test failures with `distributed/optim/test_zero_redundancy_optimizer` and `distributed/test_distributed_spawn`: http://rocmhead.amd.com:8080/job/pytorch/job/pytorch-test-distributed/16/console

**Comment by jithunnair-amd** [comment]
Unit test failures do not seem to be due to IFU. Merging.

**Pull request merged**
