### PR TITLE
Fix build_amd.py for hip-clang

### PR DESCRIPTION
**Pull request by yxsamliu**
Re-open this PR as discussed.

### CODE REVIEW

**Comment by yxsamliu** [comment]
the test failure https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-win-ws2016-cuda9-cudnn7-py3-test2/40915//console seems not related to this change.

**Comment by iotamudelta** [comment]
Agreed, failures seem unrelated to this PR.

**Pull request merged**
