### PR TITLE
IFU-rocm3.7 internal testing 08/05/2020

### PR DESCRIPTION
**Pull request by lcskrishna**

### CODE REVIEW

**Comment by jeffdaily** [comment]
`pr/caffe2-pytorch-linux-xenial-rocm3.5.1-py3.6-test` passed.  We had a rocminfo hang during pt test1, and test2 had test failures.

**Comment by jeffdaily** [comment]
test_cuda.py test_sum_fp16 and test_trilu_indices.

**Comment by lcskrishna** [comment]
@jeffdaily all the tests passed.

**Pull request merged**
