### PR TITLE
IFU-master-2022-03-30

### PR DESCRIPTION
**Pull request by hubertlu-tw**
No conflict.

### CODE REVIEW

**Comment by hubertlu-tw** [comment]
`test-distributed` runs show some unit test failures with `distributed/optim/test_zero_redundancy_optimizer` and `distributed/test_distributed_spawn`: http://rocmhead.amd.com:8080/job/pytorch/job/pytorch-test-distributed/17/artifact/pytorch_log/pytorch.test_distributed.log. But these test suites seem to run fine in upstream CI log from 3/29: https://ossci-raw-job-status.s3.amazonaws.com/log/5745638066. The two issues have been observed from the previous IFU PR (https://github.com/ROCmSoftwarePlatform/pytorch/pull/921). Please refer to the issues in the following links:
1. https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/1350
2. https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/1351

In addition, `test-1` failed with only one test `test_wishart_log_prob` in suite `distributions/test_distributions`. But this test seems to pass in upstream CI log from 3/29: https://ossci-raw-job-status.s3.amazonaws.com/log/5746688130. The issue also has been observed from the previous IFU PR (https://github.com/ROCmSoftwarePlatform/pytorch/pull/921). Please refer to the issue for further debugging here: https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/1353

**Comment by hubertlu-tw** [comment]
test pytorch/apex/torchvision please

**Comment by hubertlu-tw** [comment]
- [apex_extension_unittest_ifu.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/8422573/apex_extension_unittest_ifu.txt)

- [apex_unittest_ifu.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/8422574/apex_unittest_ifu.txt)

- [apex_distributed_unittest_ifu.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/8422577/apex_distributed_unittest_ifu.txt)

- [torchvision_unittest_ifu.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/8422576/torchvision_unittest_ifu.txt)

**Comment by hubertlu-tw** [comment]
The torchvision unit test results can be found here:
[torchvision_unittest_ifu.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/8430455/torchvision_unittest_ifu.txt)
It used the torhcvision commit in [related_commits](https://github.com/ROCmSoftwarePlatform/pytorch/blob/IFU-master-2022-03-30/related_commits#L3).
It failed one test as follows:
```
XFAIL test/test_transforms.py::test_max_value_iinfo
  torch.iinfo() is not supported by torchscript. See https://github.com/pytorch/pytorch/issues/41492.
```

**Comment by jithunnair-amd** [comment]
PyTorch build passed in CI job: http://rocmhead.amd.com:8080/job/pytorch/job/pytorch-ci/235/ for commit [8796aad](https://github.com/ROCmSoftwarePlatform/pytorch/pull/981/commits/8796aad30f314a11cfaeead80b90ce6c6fc934f8)
PyTorch unit test failures were detailed in https://github.com/ROCmSoftwarePlatform/pytorch/pull/981#issuecomment-1084816288
Torchvision commit was updated in related_commits and tests passed except one test as detailed here: https://github.com/ROCmSoftwarePlatform/pytorch/pull/981#issuecomment-1090790170

**Pull request merged**
