### PR TITLE
[SOW MS3] Fix test_non_standard_bool_values_any_cuda_bool

### PR DESCRIPTION
**Pull request by jaglinux**
Port actual commit code of PR 78957 + exclude
torch/testing/_internal/common_methods_invocations.py so that actual tests are not modified.

Signed-off-by: Jagadish Krishnamoorthy <jagdish.krishna@gmail.com>

### CODE REVIEW

**Comment by jaglinux** [comment]
18:43:52 Aug 12 01:43:52   test_non_standard_bool_values_any_cuda_bool (__main__.TestCommonCUDA) ... ok (0.007s)

**Comment by pruthvistony** [comment]
@jaglinux ,
Please check all cases  - https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/2338

**Comment by jaglinux** [comment]
@pruthvistony all the test cases mentioned are passing in this PR build.
18:43:52 Aug 12 01:43:52   test_non_standard_bool_values_argwhere_cuda_bool (__main__.TestCommonCUDA) ... ok (0.005s)
18:43:52 Aug 12 01:43:52   test_non_standard_bool_values_bitwise_not_cuda_bool (__main__.TestCommonCUDA) ... ok (0.003s)
18:43:52 Aug 12 01:43:52   test_non_standard_bool_values_logical_not_cuda_bool (__main__.TestCommonCUDA) ... ok (0.003s)
18:43:53 Aug 12 01:43:53   test_non_standard_bool_values_masked_select_cuda_bool (__main__.TestCommonCUDA) ... ok (0.254s)
18:43:52 Aug 12 01:43:52   test_non_standard_bool_values_any_cuda_bool (__main__.TestCommonCUDA) ... ok (0.007s)
18:43:53 Aug 12 01:43:53   test_non_standard_bool_values_nonzero_cuda_bool (__main__.TestCommonCUDA) ... ok (0.014s)

**Comment by jaglinux** [comment]
@jithunnair-amd @pruthvistony This PR is good to merge.

**Comment by jithunnair-amd** [comment]
From offline discussion with @jaglinux:
This PR has the fix for test_non_standard_bool_values_any_cuda_bool on sow_ms3 branch with ROCm5.2.
Running the above 6 tests in ROCm 5.3, we are seeing 2 failures. Still debugging those. Most likely will involve a patch on top of this PR.

**Comment by jaglinux** [comment]
This PR is required to fix test_non_standard_bool_values_any_cuda_bool.
On ROCm 5.3, this PR fixes the accuracy errors found in https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/2338 
The "shape' do not match" errors on few test_non_standard_bool_values* tests are found on only ROCm 5.3, with our without this PR.
The error is also found on upstream Pytorch branch on latest ROCm mainline. However on ROCm 5.2, the error does not occur.
I would recommend this PR and continue to debug "shape' do not match" errors on ROCm5.3 / mainline.
Error log : AssertionError: The values for attribute 'shape' do not match: torch.Size([1, 0]) != torch.Size([165, 0]).

**Comment by jaglinux** [comment]
The failures on ROCm 5.3 / mainline is tracked by https://ontrack-internal.amd.com/browse/SWDEV-344137

**Review by jithunnair-amd — APPROVED** [review]

**Pull request merged**
