### PR TITLE
IFU-master 07/30/2020.

### PR DESCRIPTION
**Pull request by lcskrishna**

### CODE REVIEW

**Comment by lcskrishna** [comment]
Build timed out 
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-xenial-rocm3.5.1-py3.6-test2/2203/console

@pytorchbot retest this please.

**Comment by ashishfarmer** [comment]
Timeouts again:
https://ci.pytorch.org/jenkins/job/caffe2-builds/job/pytorch-linux-xenial-rocm3.5.1-py3.6-test/2251/console
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-xenial-rocm3.5.1-py3.6-test1/2246/console

**Comment by sunway513** [comment]
let's take a step back. If you run the CI scripts locally, will you see timeout?

**Comment by jeffdaily** [comment]
IFU into testing branch worked ok.  #702

**Comment by jeffdaily** [comment]
Closing in favor of #704 .

**Pull request closed without merging**
