### PR TITLE
IFU-master-2022-04-11

### PR DESCRIPTION
**Pull request by rraminen**
No conflict

### CODE REVIEW

**Comment by rraminen** [comment]
test pytorch/apex/torchvision please

**Comment by rraminen** [comment]
As the CI is on ROCm 5.0, the PyTorch unit tests are tested locally on ROCm 5.1 release image. 

The below 4 tests fail because of packaging error: (https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/1530)
> test_loading_pickle (test_directory_reader.DirectoryReaderTest)
> test_model_save (test_model.ModelTest)
>  test_resnet (test_model.ModelTest)
>  test_script_resnet (test_model.ModelTest)
 
The below 2 unit tests fail with proxy related errors: (https://github.com/ROCmSoftwarePlatform/frameworks-internal/issues/1531)
> test_torchvision_models_detection_ssd300_vgg16 (__main__.TestVisionTracing)
> test_torchvision_models_detection_ssdlite320_mobilenet_v3_large (__main__.TestVisionTracing)

The below 3 tests fail, but there are skipped for now as we are aware of this issue:
> test_event_handle_exporter (__main__.TestMultiprocessing) 
> test_event_handle_importer (__main__.TestMultiprocessing)
> test_event_multiprocess (__main__.TestMultiprocessing)



Among the distributed unit tests, the below two tests fail but can be ignored as there are disabled in the upstream CI:
> test_post_localSGD_optimizer_parity_with_hierarchical_sgd (__main__.TestDistBackendWithSpawn)
> test_post_localSGD_optimizer_parity_with_hierarchical_sgd_grad_is_view (__main__.TestDistBackendWithSpawn)

[PT_unittests_log_IFU-master-2022-04-11.log](https://github.com/ROCmSoftwarePlatform/pytorch/files/8510523/PT_unittests_log_IFU-master-2022-04-11.log)

[PT_unittests_log_IFU-master-2022-04-11_distributed.log](https://github.com/ROCmSoftwarePlatform/pytorch/files/8510524/PT_unittests_log_IFU-master-2022-04-11_distributed.log)

**Comment by rraminen** [comment]
http://rocmhead.amd.com:8080/job/pytorch/job/pytorch-ci/22/

Apex unit tests look good
[apex.test.log](https://github.com/ROCmSoftwarePlatform/pytorch/files/8516728/apex.test.log)

Torchvision unit tests look good
[torchvision.test.log](https://github.com/ROCmSoftwarePlatform/pytorch/files/8516727/torchvision.test.log)

They used https://github.com/ROCmSoftwarePlatform/pytorch/pull/993/commits/0e487f5d028537b2620f15fbf1ebabb64bc21c50

**Comment by pruthvistony** [comment]
test pytorch/apex/torchvision please

**Review by pruthvistony — APPROVED** [review]

**Comment by pruthvistony** [comment]
@rraminen , can you push an empty commit to trigger the CI.
The previous failure is in ld while building torchvision.

**Comment by rraminen** [comment]
Hi @pruthvistony, I pushed an empty commit.

**Pull request merged**
