### PR TITLE
Updating default shard values in test.sh

### PR DESCRIPTION
**Pull request by pragupta**
Fixes #ISSUE_NUMBER

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
@pragupta Why update triton.txt? Do we use it anywhere? We use https://github.com/ROCmSoftwarePlatform/pytorch/blob/rocm6.0_internal_testing/.ci/docker/ci_commit_pins/triton-rocm.txt for ROCm flow.

Also, why do we need the default values to be added to test.sh? Does that trigger some CI logic you're trying to exercise? Please point to a link, if so.

**Comment by pragupta** [comment]
Woops.. my bad on the triton.txt. I didn't that there was triton-rocm.txt as well. I will remove it. 

It seems that the inductor tests run when both TEST_CONFIG and SHARD_NUMBER variables are set, but by default there should at least be 1 shard. So, @pruthvistony suggested that it'd be cleaner if we just added default values for these. Obviously, alternatively, I can pass them through command line. 

https://github.com/ROCmSoftwarePlatform/pytorch/blob/1ad7bb843085e6f598ead05abaa44949260b61ab/.ci/pytorch/test.sh#L1043

**Comment by pruthvistony** [comment]
`"$TEST_CONFIG" == distributed `  is also having same problem, so this change helps.
Can we raise this to upstream also, I am not sure of the affect on CUDA jobs so may be keep it for only ROCm jobs. Please check on it.

Note: I edited the PR title to reflect the change.

**Comment by pruthvistony** [comment]
@pragupta ,
On a side note did you check on `test_inductor_distributed` tests which are triggerd by TEST_CONFIG=inductor

**Review by pruthvistony — APPROVED** [review]

**Comment by jithunnair-amd** [comment]
> Woops.. my bad on the triton.txt. I didn't that there was triton-rocm.txt as well. I will remove it.
> 
> It seems that the inductor tests run when both TEST_CONFIG and SHARD_NUMBER variables are set, but by default there should at least be 1 shard. So, @pruthvistony suggested that it'd be cleaner if we just added default values for these. Obviously, alternatively, I can pass them through command line.
> 
> https://github.com/ROCmSoftwarePlatform/pytorch/blob/1ad7bb843085e6f598ead05abaa44949260b61ab/.ci/pytorch/test.sh#L1043

Actually, we specify the TEST_CONFIG and SHARD_NUMBER env vars in our CI run scripts even for the default ( [TEST_CONFIG](https://github.com/ROCmSoftwarePlatform/rocAutomation/blob/163f8e8efd97793f8f7edf9d882c7fe553921bbb/pytorch/pytorch_ci/test_pytorch_test1.sh#L18) and [SHARD_NUMBER](https://github.com/ROCmSoftwarePlatform/rocAutomation/blob/163f8e8efd97793f8f7edf9d882c7fe553921bbb/pytorch/pytorch_ci/test_pytorch_test1.sh#L74) and distributed ([TEST_CONFIG](https://github.com/ROCmSoftwarePlatform/rocAutomation/blob/163f8e8efd97793f8f7edf9d882c7fe553921bbb/pytorch/pytorch_ci/test_pytorch_test_distributed_1.sh#L18) and [SHARD_NUMBER](https://github.com/ROCmSoftwarePlatform/rocAutomation/blob/163f8e8efd97793f8f7edf9d882c7fe553921bbb/pytorch/pytorch_ci/test_pytorch_test_distributed_1.sh#L75)) runs, so specifying on the command line would be consistent.

**Comment by jithunnair-amd** [comment]
> `"$TEST_CONFIG" == distributed ` is also having same problem, so this change helps. Can we raise this to upstream also, I am not sure of the affect on CUDA jobs so may be keep it for only ROCm jobs. Please check on it.
> 
> Note: I edited the PR title to reflect the change.

Can you please clarify what is the issue seen with the TEST_CONFIG="distributed" runs? We are already specifying the SHARD_NUMBER for distributed runs as well.

**Comment by pruthvistony** [comment]
> > `"$TEST_CONFIG" == distributed ` is also having same problem, so this change helps. Can we raise this to upstream also, I am not sure of the affect on CUDA jobs so may be keep it for only ROCm jobs. Please check on it.
> > Note: I edited the PR title to reflect the change.
> 
> Can you please clarify what is the issue seen with the TEST_CONFIG="distributed" runs? We are already specifying the SHARD_NUMBER for distributed runs as well.

`TEST_CONFIG="default"` can execute without providing any SHARD_NUMBER, so want to get the same behaviour for `TEST_CONFIG="distributed"` and `TEST_CONFIG="inductor"` leading to simpler QA instructions.

Also QA is running on single machine, so having multiple shards doesnt help.

**Comment by pragupta** [comment]
> @pragupta , On a side note did you check on `test_inductor_distributed` tests which are triggerd by TEST_CONFIG=inductor

Yes, I did run those. They seemed to run fine. 

@pruthvistony -- So, are we okay with specifying SHARD_NUMBER on command line?

**Comment by jithunnair-amd** [comment]
> > > `"$TEST_CONFIG" == distributed ` is also having same problem, so this change helps. Can we raise this to upstream also, I am not sure of the affect on CUDA jobs so may be keep it for only ROCm jobs. Please check on it.
> > > Note: I edited the PR title to reflect the change.
> > 
> > 
> > Can you please clarify what is the issue seen with the TEST_CONFIG="distributed" runs? We are already specifying the SHARD_NUMBER for distributed runs as well.
> 
> `TEST_CONFIG="default"` can execute without providing any SHARD_NUMBER, so want to get the same behaviour for `TEST_CONFIG="distributed"` and `TEST_CONFIG="inductor"` leading to simpler QA instructions.
> 
> Also QA is running on single machine, so having multiple shards doesnt help.

Okay, I see your point now from QA's perspective:
TEST_CONFIG=distributed: https://github.com/ROCmSoftwarePlatform/pytorch/blob/a49a6a0d1cbd5bb696e40f01901af1ec8beff144/.ci/pytorch/test.sh#L999
and
TEST_CONFIG=inductor:
https://github.com/ROCmSoftwarePlatform/pytorch/blob/a49a6a0d1cbd5bb696e40f01901af1ec8beff144/.ci/pytorch/test.sh#L1038

**Pull request merged**
