### PR TITLE
Disable NVFuser in test_jit_cuda_fuser and skip failing UT

### PR DESCRIPTION
**Pull request by jataylo**
The commit at https://github.com/ROCmSoftwarePlatform/pytorch/commit/5d42d167161fe15ba767fcd7ab9f573fa32b2284 does not disable NVFuser in test_jit_cuda_fuser.py as it is explicitly enabled:
`self.old_nvfuser = torch._C._jit_set_nvfuser_enabled(True)`

This commit will explicitly disable in rocm5.4_internal_testing in the file for ROCm and will skip the test_softmax UT as this has shown to only pass with NVFuser enabled (as noted in https://ontrack-internal.amd.com/browse/SWDEV-361875)

Can be reverted once NVFuser fixes are up

### CODE REVIEW

**Comment by jataylo** [comment]
Note: leave the CI running for this to ensure no other fails with NVFuser now disabled

**Review by pruthvistony — APPROVED** [review]

**Review by pruthvistony — CHANGES_REQUESTED** [review]
Change looks fine, but the tests are still failing
Nov 04 15:15:17   test_single_reduction_broadcast (__main__.TestCudaFuser) ... FAIL (0.197s)
Nov 04 15:15:17   test_singleton_fusion (__main__.TestCudaFuser) ... FAIL (0.194s)
Nov 04 15:15:17   test_skip_parser (__main__.TestCudaFuser) ... FAIL (0.196s)
Nov 04 15:15:17   test_softmax (__main__.TestCudaFuser) ... skip: test is slow; run with PYTORCH_TEST_WITH_SLOW to enable test (0.001s)
Nov 04 15:15:17   test_softmax_bfloat (__main__.TestCudaFuser) ... FAIL (0.203s)
Nov 04 15:15:17   test_softmax_dtype (__main__.TestCudaFuser) ... FAIL (0.229s)
Nov 04 15:15:18   test_softmax_half (__main__.TestCudaFuser) ... FAIL (0.201s)
Nov 04 15:15:18   test_softplus_fuser (__main__.TestCudaFuser) ... FAIL (0.215s)

**Comment by jataylo** [comment]
@pruthvistony @jeffdaily @jithunnair-amd 
Explicitly disabling NVfuser seems to lead to multiple fails in this UT suite also. May need to revert https://github.com/ROCmSoftwarePlatform/pytorch/commit/d09486ab233284e9f298e45a43977fed8f075fe4
Nov 04 15:15:17 test_single_reduction_broadcast (main.TestCudaFuser) ... FAIL (0.197s)
Nov 04 15:15:17 test_singleton_fusion (main.TestCudaFuser) ... FAIL (0.194s)
Nov 04 15:15:17 test_skip_parser (main.TestCudaFuser) ... FAIL (0.196s)
Nov 04 15:15:17 test_softmax (main.TestCudaFuser) ... skip: test is slow; run with PYTORCH_TEST_WITH_SLOW to enable test (0.001s)
Nov 04 15:15:17 test_softmax_bfloat (main.TestCudaFuser) ... FAIL (0.203s)
Nov 04 15:15:17 test_softmax_dtype (main.TestCudaFuser) ... FAIL (0.229s)
Nov 04 15:15:18 test_softmax_half (main.TestCudaFuser) ... FAIL (0.201s)
Nov 04 15:15:18 test_softplus_fuser (main.TestCudaFuser) ... FAIL (0.215s)

**Comment by jataylo** [comment]
New PR open that follows from this - will add the UT file to ROCM_BLOCKLIST
https://github.com/ROCmSoftwarePlatform/pytorch/pull/1139

**Pull request closed without merging**
