### PR TITLE
backwards apex layer_norm cherry pick 

### PR DESCRIPTION
**Pull request by jataylo**
Cherry picks upstream updates to the Apex layer_norm port.
https://github.com/pytorch/pytorch/pull/87635 
https://github.com/pytorch/pytorch/pull/87726

### CODE REVIEW

**Review by hubertlu-tw — APPROVED** [review]
LGTM. 
However, as @jataylo found that there is a deprecated `__HIP_PLATFORM_HCC__` used in [line #1166](https://github.com/ROCmSoftwarePlatform/pytorch/blob/32c760c2bb8215f5f13553abdbfd9cbcab625a80/aten/src/ATen/native/cuda/layer_norm_kernel.cu#L1166), we will need to create another PR to replace it with `USE_ROCM` in upstream PyTorch in the future.

**Comment by jataylo** [comment]
Fails are unrelated. pytorch-test-distributed-1 did not run, retrying.
```
Dec 06 19:28:52 ======================================================================
Dec 06 19:28:52 ERROR [0.003s]: test_adamax (__main__.TestOptim)
Dec 06 19:28:52 ----------------------------------------------------------------------
Dec 06 19:28:52 Traceback (most recent call last):
Dec 06 19:28:52   File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 2037, in setUp
Dec 06 19:28:52     check_if_enable(self)
Dec 06 19:28:52   File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 1626, in check_if_enable
Dec 06 19:28:52     if platforms == [] or any([platform_to_conditional[platform] for platform in platforms]):
Dec 06 19:28:52   File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 1626, in <listcomp>
Dec 06 19:28:52     if platforms == [] or any([platform_to_conditional[platform] for platform in platforms]):
Dec 06 19:28:52 KeyError: 'dynamo'
Dec 06 19:28:52 
Dec 06 19:28:52 ======================================================================
Dec 06 19:28:52 ERROR [0.003s]: test_adamw (__main__.TestOptim)
Dec 06 19:28:52 ----------------------------------------------------------------------
Dec 06 19:28:52 Traceback (most recent call last):
Dec 06 19:28:52   File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 2037, in setUp
Dec 06 19:28:52     check_if_enable(self)
Dec 06 19:28:52   File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 1626, in check_if_enable
Dec 06 19:28:52     if platforms == [] or any([platform_to_conditional[platform] for platform in platforms]):
Dec 06 19:28:52   File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 1626, in <listcomp>
Dec 06 19:28:52     if platforms == [] or any([platform_to_conditional[platform] for platform in platforms]):
Dec 06 19:28:52 KeyError: 'dynamo'
Dec 06 19:28:52 
Dec 06 19:28:52 ======================================================================
Dec 06 19:28:52 ERROR [0.002s]: test_asgd (__main__.TestOptim)
Dec 06 19:28:52 ----------------------------------------------------------------------
Dec 06 19:28:52 Traceback (most recent call last):
Dec 06 19:28:52   File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 2037, in setUp
Dec 06 19:28:52     check_if_enable(self)
Dec 06 19:28:52   File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 1626, in check_if_enable
Dec 06 19:28:52     if platforms == [] or any([platform_to_conditional[platform] for platform in platforms]):
Dec 06 19:28:52   File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 1626, in <listcomp>
Dec 06 19:28:52     if platforms == [] or any([platform_to_conditional[platform] for platform in platforms]):
Dec 06 19:28:52 KeyError: 'dynamo'
Dec 06 19:28:52 
Dec 06 19:28:52 ======================================================================
Dec 06 19:28:52 ERROR [0.004s]: test_nadam (__main__.TestOptim)
Dec 06 19:28:52 ----------------------------------------------------------------------
Dec 06 19:28:52 Traceback (most recent call last):
Dec 06 19:28:52   File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 2037, in setUp
Dec 06 19:28:52     check_if_enable(self)
Dec 06 19:28:52   File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 1626, in check_if_enable
Dec 06 19:28:52     if platforms == [] or any([platform_to_conditional[platform] for platform in platforms]):
Dec 06 19:28:52   File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 1626, in <listcomp>
Dec 06 19:28:52     if platforms == [] or any([platform_to_conditional[platform] for platform in platforms]):
Dec 06 19:28:52 KeyError: 'dynamo'
Dec 06 19:28:52 
Dec 06 19:28:52 ======================================================================
Dec 06 19:28:52 ERROR [0.003s]: test_radam (__main__.TestOptim)
Dec 06 19:28:52 ----------------------------------------------------------------------
Dec 06 19:28:52 Traceback (most recent call last):
Dec 06 19:28:52   File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 2037, in setUp
Dec 06 19:28:52     check_if_enable(self)
Dec 06 19:28:52   File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 1626, in check_if_enable
Dec 06 19:28:52     if platforms == [] or any([platform_to_conditional[platform] for platform in platforms]):
Dec 06 19:28:52   File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 1626, in <listcomp>
Dec 06 19:28:52     if platforms == [] or any([platform_to_conditional[platform] for platform in platforms]):
Dec 06 19:28:52 KeyError: 'dynamo'
Dec 06 19:28:52 
Dec 06 19:28:52 ======================================================================
Dec 06 19:28:52 ERROR [0.006s]: test_rmsprop (__main__.TestOptim)
Dec 06 19:28:52 ----------------------------------------------------------------------
Dec 06 19:28:52 Traceback (most recent call last):
Dec 06 19:28:52   File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 2037, in setUp
Dec 06 19:28:52     check_if_enable(self)
Dec 06 19:28:52   File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 1626, in check_if_enable
Dec 06 19:28:52     if platforms == [] or any([platform_to_conditional[platform] for platform in platforms]):
Dec 06 19:28:52   File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 1626, in <listcomp>
Dec 06 19:28:52     if platforms == [] or any([platform_to_conditional[platform] for platform in platforms]):
Dec 06 19:28:52 KeyError: 'dynamo'
Dec 06 19:28:52 
Dec 06 19:28:52 ----------------------------------------------------------------------
Dec 06 19:28:52 Ran 146 tests in 102.799s
Dec 06 19:28:52 
Dec 06 19:28:52 FAILED (errors=6, skipped=1)
```

```
Dec 06 18:31:50 ======================================================================
Dec 06 18:31:50 ERROR [0.003s]: test_versioned_div_tensor_inplace (jit.test_save_load_for_op_version.TestSaveLoadForOpVersion)
Dec 06 18:31:50 ----------------------------------------------------------------------
Dec 06 18:31:50 Traceback (most recent call last):
Dec 06 18:31:50   File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/jit_utils.py", line 140, in setUp
Dec 06 18:31:50     super().setUp()
Dec 06 18:31:50   File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 2037, in setUp
Dec 06 18:31:50     check_if_enable(self)
Dec 06 18:31:50   File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 1626, in check_if_enable
Dec 06 18:31:50     if platforms == [] or any([platform_to_conditional[platform] for platform in platforms]):
Dec 06 18:31:50   File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 1626, in <listcomp>
Dec 06 18:31:50     if platforms == [] or any([platform_to_conditional[platform] for platform in platforms]):
Dec 06 18:31:50 KeyError: 'dynamo'
Dec 06 18:31:50 
Dec 06 18:31:51 ----------------------------------------------------------------------

Dec 06 18:37:47 =================================== FAILURES ===================================
Dec 06 18:37:47 _______ TestCommonCUDA.test_non_standard_bool_values_argwhere_cuda_bool ________
Dec 06 18:37:47 [gw1] linux -- Python 3.8.13 /opt/conda/bin/python
Dec 06 18:37:47 Traceback (most recent call last):
Dec 06 18:37:47   File "/var/lib/jenkins/pytorch/test/test_ops.py", line 1057, in test_non_standard_bool_values
Dec 06 18:37:47     self.assertEqual(expect, actual)
Dec 06 18:37:47   File "/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_utils.py", line 2401, in assertEqual
Dec 06 18:37:47     assert_equal(
Dec 06 18:37:47   File "/opt/conda/lib/python3.8/site-packages/torch/testing/_comparison.py", line 1093, in assert_equal
Dec 06 18:37:47     raise error_metas[0].to_error(msg)
Dec 06 18:37:47 AssertionError: The values for attribute 'shape' do not match: torch.Size([2, 1]) != torch.Size([290, 1]).
Dec 06 18:37:47 - generated xml file: /var/lib/jenkins/pytorch/test/test-reports/python-pytest/test_ops/test_ops.xml -
```

**Comment by jataylo** [comment]
This should be targeted to 5.5 instead. Another new PR open at https://github.com/ROCmSoftwarePlatform/pytorch/pull/1148

**Comment by pruthvistony** [comment]
Can we close this PR, assuming it is not required.

**Comment by jataylo** [comment]
> Can we close this PR, assuming it is not required.

Closed. Thanks for the reminder.

**Pull request closed without merging**
