### PR TITLE
[ROCm] unskip test_jit TestBackendsWithCompiler

### PR DESCRIPTION
**Pull request by jeffdaily**

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
retest this please

**Review by jithunnair-amd — APPROVED** [review]
LGTM. Waiting for CI.

**Comment by jithunnair-amd** [comment]
retest this please

**Comment by jithunnair-amd** [comment]
http://rocmhead.amd.com:8080/job/pytorch/job/pytorch-test-1/103/consoleFull
```
00:25:41.305   test_errors (jit.test_backends.TestBackendsWithCompiler) ... ok (0.056s)
00:25:41.363   test_execution (jit.test_backends.TestBackendsWithCompiler) ... ok (0.053s)
```

**Comment by jithunnair-amd** [comment]
@jeffdaily Are there any other unit tests that you expected to be enabled via this PR? If so, can you please post the snippet and log link for that here as well?

**Comment by jeffdaily** [comment]
> @jeffdaily Are there any other unit tests that you expected to be enabled via this PR? If so, can you please post the snippet and log link for that here as well?

Just the two tests you already posted the snippet for.

**Pull request merged**
