### PR TITLE
Removed unrecognized command line options for HIP - release/2.0

### PR DESCRIPTION
**Pull request by jataylo**
Remove the outdated HIP flags appended to HIP_CXX_FLAGS

This will remove the following warnings in the pytorch build log

```
[3302/5055] Building CXX object c10/hip/CMakeFiles/c10_hip.dir/HIPMiscFunctions.cpp.o
cc1plus: warning: command line option ‘-Wno-duplicate-decl-specifier’ is valid for C/ObjC but not for C++
cc1plus: warning: unrecognized command line option ‘-Wno-implicit-int-float-conversion’
cc1plus: warning: unrecognized command line option ‘-Wno-unused-command-line-argument’
cc1plus: warning: unrecognized command line option ‘-Wno-exceptions’
cc1plus: warning: unrecognized command line option ‘-Wno-inconsistent-missing-override’
cc1plus: warning: unrecognized command line option ‘-Wno-macro-redefined’
```

Original PR for release/1.10.1 branch
https://github.com/ROCmSoftwarePlatform/pytorch/pull/1218

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
@jeffdaily When you force-pushed the `release/2.0` branch to contain the `release/2.0.1` commits, it looks like you didn't retain the cherry-picks we had made to `release/2.0` branch?

**Comment by jeffdaily** [comment]
> @jeffdaily When you force-pushed the `release/2.0` branch to contain the `release/2.0.1` commits, it looks like you didn't retain the cherry-picks we had made to `release/2.0` branch? [04ee2b9...a0206c1](https://github.com/ROCmSoftwarePlatform/pytorch/compare/04ee2b9e1265ddc1bc9a2d94ddd348a482f253ba...a0206c19e307ed89b712f6d049710ecb01a84992)

I swear I did a git pull to be on tip of our original release/2.0 branch (now saved as release/2.0.0), then rebased against upstream tip of release/2.0, then force pushed.  Shouldn't that have saved our cherry-picks?

**Comment by jeffdaily** [comment]
Can confirm.  Look at the commit history for these two branches and you'll see all our commits that were on top of the [original release/2.0 branch](https://github.com/ROCmSoftwarePlatform/pytorch/commits/release/2.0.0) are present in the [current release/2.0 branch](https://github.com/ROCmSoftwarePlatform/pytorch/commits/release/2.0).

**Comment by jithunnair-amd** [comment]
> Can confirm. Look at the commit history for these two branches and you'll see all our commits that were on top of the [original release/2.0 branch](https://github.com/ROCmSoftwarePlatform/pytorch/commits/release/2.0.0) are present in the [current release/2.0 branch](https://github.com/ROCmSoftwarePlatform/pytorch/commits/release/2.0).

Ah I see, thanks for clarifying. My conclusion was wrong. I think the rebase on your end made the original cherry-picked commits show up as this PR's commits. I'll try a rebase on the updated branch.

**Pull request merged**
