### PR TITLE
IFU-master-2021-09-10

### PR DESCRIPTION
**Pull request by hubertlu-tw**
IFU-master-2021-09-10

There is no merge conflicts. The reason why automatic IFU failed is because we need to have the "workflows" permission to be able to merge any changes to .github/workflows files (https://github.com/ROCmSoftwarePlatform/pytorch/runs/3581771991?check_suite_focus=true#step:5:63). 

The following logs files are for building PyTorch from this IFU branch and for PyTorch unit tests, respectively.
[build_log_IFU20210910.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/7165688/build_log_IFU20210910.txt)
[PT_unittests_log_IFU20210910.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/7165689/PT_unittests_log_IFU20210910.txt)

Notice that the docker image used for the experiments is rocm4.3_ubuntu18.04_py3.6_pytorch. We first uninstalled the pytorch built in the docker container and re-built PyTorch from this IFU branch.

### CODE REVIEW

**Review by jithunnair-amd — APPROVED** [review]

**Comment by jithunnair-amd** [comment]
@hubertlu-tw Thanks for the IFU and testing on ROCm4.3 locally.

**Comment by jithunnair-amd** [comment]
I see this in the unit test output:
```
Test results will be stored in test-reports/python-unittest/test_linalg

Intel MKL ERROR: Parameter 4 was incorrect on entry to DLASCL.

Intel MKL ERROR: Parameter 5 was incorrect on entry to DLASCL.

Intel MKL ERROR: Parameter 4 was incorrect on entry to DLASCL.

Intel MKL ERROR: Parameter 5 was incorrect on entry to DLASCL.

Intel MKL ERROR: Parameter 4 was incorrect on entry to DLASCL.

Intel MKL ERROR: Parameter 5 was incorrect on entry to DLASCL.

Intel MKL ERROR: Parameter 4 was incorrect on entry to DLASCL.

Intel MKL ERROR: Parameter 5 was incorrect on entry to DLASCL.

Intel MKL ERROR: Parameter 4 was incorrect on entry to DLASCL.

Intel MKL ERROR: Parameter 4 was incorrect on entry to DLASCL.

Intel MKL ERROR: Parameter 4 was incorrect on entry to DLASCL.

Intel MKL ERROR: Parameter 4 was incorrect on entry to DLASCL.

Intel MKL ERROR: Parameter 4 was incorrect on entry to SLASCL.

Intel MKL ERROR: Parameter 4 was incorrect on entry to SLASCL.

Intel MKL ERROR: Parameter 4 was incorrect on entry to SLASCL.

Intel MKL ERROR: Parameter 4 was incorrect on entry to SLASCL.

Intel MKL ERROR: Parameter 4 was incorrect on entry to SLASCL.

Intel MKL ERROR: Parameter 4 was incorrect on entry to SLASCL.

Intel MKL ERROR: Parameter 4 was incorrect on entry to SLASCL.

Intel MKL ERROR: Parameter 4 was incorrect on entry to SLASCL.

Intel MKL ERROR: Parameter 4 was incorrect on entry to DLASCL.

Intel MKL ERROR: Parameter 4 was incorrect on entry to DLASCL.

Intel MKL ERROR: Parameter 4 was incorrect on entry to DLASCL.

Intel MKL ERROR: Parameter 4 was incorrect on entry to DLASCL.
```

Also, the unit test results look a bit different (less verbose). What was the command you used to run these unit tests?

**Comment by jithunnair-amd** [comment]
@hubertlu-tw Could you compare the unit test results for ROCm4.2 (CI) to ROCm4.3 (local run)?

**Comment by hubertlu-tw** [comment]
> I see this in the unit test output:
> 
> ```
> Test results will be stored in test-reports/python-unittest/test_linalg
> 
> Intel MKL ERROR: Parameter 4 was incorrect on entry to DLASCL.
> 
> Intel MKL ERROR: Parameter 5 was incorrect on entry to DLASCL.
> 
> Intel MKL ERROR: Parameter 4 was incorrect on entry to DLASCL.
> 
> Intel MKL ERROR: Parameter 5 was incorrect on entry to DLASCL.
> 
> Intel MKL ERROR: Parameter 4 was incorrect on entry to DLASCL.
> 
> Intel MKL ERROR: Parameter 5 was incorrect on entry to DLASCL.
> 
> Intel MKL ERROR: Parameter 4 was incorrect on entry to DLASCL.
> 
> Intel MKL ERROR: Parameter 5 was incorrect on entry to DLASCL.
> 
> Intel MKL ERROR: Parameter 4 was incorrect on entry to DLASCL.
> 
> Intel MKL ERROR: Parameter 4 was incorrect on entry to DLASCL.
> 
> Intel MKL ERROR: Parameter 4 was incorrect on entry to DLASCL.
> 
> Intel MKL ERROR: Parameter 4 was incorrect on entry to DLASCL.
> 
> Intel MKL ERROR: Parameter 4 was incorrect on entry to SLASCL.
> 
> Intel MKL ERROR: Parameter 4 was incorrect on entry to SLASCL.
> 
> Intel MKL ERROR: Parameter 4 was incorrect on entry to SLASCL.
> 
> Intel MKL ERROR: Parameter 4 was incorrect on entry to SLASCL.
> 
> Intel MKL ERROR: Parameter 4 was incorrect on entry to SLASCL.
> 
> Intel MKL ERROR: Parameter 4 was incorrect on entry to SLASCL.
> 
> Intel MKL ERROR: Parameter 4 was incorrect on entry to SLASCL.
> 
> Intel MKL ERROR: Parameter 4 was incorrect on entry to SLASCL.
> 
> Intel MKL ERROR: Parameter 4 was incorrect on entry to DLASCL.
> 
> Intel MKL ERROR: Parameter 4 was incorrect on entry to DLASCL.
> 
> Intel MKL ERROR: Parameter 4 was incorrect on entry to DLASCL.
> 
> Intel MKL ERROR: Parameter 4 was incorrect on entry to DLASCL.
> ```
> 
> Also, the unit test results look a bit different (less verbose). What was the command you used to run these unit tests?

I used `.jenkins/pytorch/test.sh` to run the unit tests.

**Comment by hubertlu-tw** [comment]
> @hubertlu-tw Could you compare the unit test results for ROCm4.2 (CI) to ROCm4.3 (local run)?

@jithunnair-amd Please find the updated log file of the unit test results for ROCm4.3 (local run) here ([unittest_local_4.3.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/7173585/unittest_local_4.3.txt)). The unit test results for ROCm4.2 (CI) can be found [pytorch-linux-bionic-rocm4.2-py3.6-test1](https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.2-py3.6-test1/19070/timestamps/?time=HH:mm:ss&appendLog&locale=en_US) and [pytorch-linux-bionic-rocm4.2-py3.6-test2](https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.2-py3.6-test2/19068/timestamps/?time=HH:mm:ss&appendLog&locale=en_US). After filtering out the log files ([local_errors.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/7173605/local_errors.txt), [CI_test1_errors.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/7173606/CI_test1_errors.txt), [CI_test2_errors.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/7173607/CI_test2_errors.txt)), we can find that ROCm4.2 and ROCm4.3 have the same unit tests results.

Notice that besides some warning messages, the errors of "Intel MKL ERROR: Parameter 4 was incorrect on entry to DLASCL." require further investigations.

**Comment by jithunnair-amd** [comment]
Merging this IFU, as it seems the MKL errors in unit tests are NOT introduced by this IFU. Will need to investigate if that is fixed by updating the Magma commit in https://github.com/pytorch/pytorch/pull/65203

**Comment by hubertlu-tw** [comment]
@jithunnair-amd Please see the attached files for the error messages and tests which are related to Intel MKL ERROR, respectively.

[MKL_related_error_messages.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/7206389/MKL_related_error_messages.txt)
[tests_related_to_MKL_errors.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/7206390/tests_related_to_MKL_errors.txt)

**Pull request merged**
