### PR TITLE
Remove ReduceMax hack for HIP that's no longer needed

### PR DESCRIPTION
**Pull request by jithunnair-amd**

### CODE REVIEW

**Comment by iotamudelta** [comment]
flaky CI

@pytorchbot retest this please

**Comment by iotamudelta** [comment]
@jithunnair-amd looks like this is still needed, no?

**Comment by jithunnair-amd** [comment]
rocm failure _maybe_, but the linux-xenial-cuda9 one is probably a flaky CI one
@pytorchbot retest this please

**Comment by iotamudelta** [comment]
@jithunnair-amd looks like for whatever reason this is still needed. Should probably be revisited eventually.

**Comment by jithunnair-amd** [comment]
Yes, I'll be debugging the one test that failed with this fix. Let's keep the PR open if that's okay.

**Comment by iotamudelta** [comment]
absolutely.

**Comment by jithunnair-amd** [comment]
That's great!

**Pull request merged**
