### PR TITLE
IFU-master-2022-06-03

### PR DESCRIPTION
**Pull request by amathews-amd**
No conflicts

### CODE REVIEW

**Comment by amathews-amd** [comment]
retest pytorch/apex/torchvision please

**Comment by amathews-amd** [comment]
retest pytorch/apex/torchvision please

**Comment by amathews-amd** [comment]
retest pytorch/apex/torchvision please

**Comment by amathews-amd** [comment]
@pruthvistony @jithunnair-amd : Passing CI: http://rocmhead.amd.com:8080/job/pytorch/job/pytorch-ci/91/

**Comment by jithunnair-amd** [comment]
@amathews-amd Did you do anything to fix the numpy error in the earlier runs, or did it resolve itself? It would appear as the following warning but then tests would fail saying `RuntimeError: Numpy is not available`:
```
/opt/conda/lib/python3.7/site-packages/torch/random.py:42: UserWarning: Failed to initialize NumPy: module compiled against API version 0xe but this version of numpy is 0xd (Triggered internally at  /var/lib/jenkins/pytorch/torch/csrc/utils/tensor_numpy.cpp:68.)
```

**Comment by jithunnair-amd** [comment]
retest pytorch/apex/torchvision please

**Comment by jithunnair-amd** [comment]
retest pytorch/apex/torchvision please

**Comment by jithunnair-amd** [comment]
retest pytorch/apex/torchvision please

**Comment by jithunnair-amd** [comment]
retest pytorch/apex/torchvision please

**Comment by jithunnair-amd** [comment]
retest pytorch/apex/torchvision please

**Comment by jithunnair-amd** [comment]
retest pytorch/apex/torchvision please

**Comment by jithunnair-amd** [comment]
retest pytorch please

**Comment by jithunnair-amd** [comment]
retest pytorch please

**Comment by jithunnair-amd** [comment]
retest pytorch please

**Comment by jithunnair-amd** [comment]
Failed with gitlab access error

retest pytorch please

**Comment by jithunnair-amd** [comment]
custom test artifact seems to work. Now making sure `numpy not found` errors (due to numpy version mismatch between build and test docker images on different hosts) don't appear: http://rocmhead.amd.com:8080/job/pytorch/job/pytorch-test-distributed-2/31/console. Hopefully, this will also fix the mysterious torchvision build failure: http://rocmhead.amd.com:8080/job/pytorch/job/pytorch-test-1/62/console

**Comment by jithunnair-amd** [comment]
retest pytorch please

**Comment by jithunnair-amd** [comment]
Last CI run: http://rocmhead.amd.com:8080/job/pytorch/job/pytorch-ci/108/consoleFull
### test-1
Failed due to test_shape_ops SIGKILL: http://rocmhead.amd.com:8080/job/pytorch/job/pytorch-test-1/66/consoleFull
Known issue running `TestShapeOpsCUDA.test_flip_large_tensor_cuda` on machine with RAM<=64G: https://ontrack-internal.amd.com/browse/SWDEV-335300
Ran locally on workstation with 256G memory and test_shape_ops passed.
[pytorch.test_shape_ops.log](https://github.com/ROCmSoftwarePlatform/pytorch/files/8971155/pytorch.test_shape_ops.log)

### test-2
Failed due to torchvision build failure: http://rocmhead.amd.com:8080/job/pytorch/job/pytorch-test-2/66/consoleFull
Ran locally without issues: 
[pytorch.test2.log](https://github.com/ROCmSoftwarePlatform/pytorch/files/8971161/pytorch.test2.log)

### test-distributed-1
Passed: http://rocmhead.amd.com:8080/job/pytorch/job/pytorch-test-distributed-1/42/consoleFull

### test-distributed-2
Failed due to timeout: http://rocmhead.amd.com:8080/job/pytorch/job/pytorch-test-distributed-2/35/console
Ran locally to completion with only test_c10d_gloo failing, but those tests seem flaky on rerunning locally. Also, they pass upstream as of Jun 23: https://ossci-raw-job-status.s3.amazonaws.com/log/7024365275
```
AssertionError: 11 unit test(s) failed:
        ProcessGroupGlooTest.test_allgather_basics_cuda
        ProcessGroupGlooTest.test_allgather_stress_cuda
        ProcessGroupGlooTest.test_allreduce_basics_cuda
        ProcessGroupGlooTest.test_allreduce_basics_cuda_using_work_api
        ProcessGroupGlooTest.test_allreduce_stress_cuda
        ProcessGroupGlooTest.test_broadcast_basics_cuda
        ProcessGroupGlooTest.test_broadcast_stress_cuda
        ProcessGroupGlooTest.test_gather_stress_cuda
        ProcessGroupGlooTest.test_reduce_basics_cuda
        ProcessGroupGlooTest.test_reduce_stress_cuda
        ProcessGroupGlooTest.test_sparse_allreduce_basics_cuda
```
[pytorch.test_distributed.test2.log](https://github.com/ROCmSoftwarePlatform/pytorch/files/8971174/pytorch.test_distributed.test2.log)

**Pull request merged**
