### PR TITLE
Refactor unit test skip statements to use @skipIfRocm annotation

### PR DESCRIPTION
**Pull request by jithunnair-amd**

### CODE REVIEW

**Comment by iotamudelta** [comment]
LGTM - will integrate once CI passes.

**Comment by jithunnair-amd** [comment]
Okay, missed an import. Fixing.

**Comment by jithunnair-amd** [comment]
hmm, what a pain :/

**Comment by jithunnair-amd** [comment]
@iotamudelta W00t! :)

**Pull request merged**
