### PR TITLE
IFU-master-2022-05-17

### PR DESCRIPTION
**Pull request by amathews-amd**
IFU 

[conflicts.txt](https://github.com/pytorch/pytorch/files/8670151/conflicts.txt)

### CODE REVIEW

**Comment by pruthvistony** [comment]
@amathews-amd ,
Please update test logs from your local machine if you have executed it.

**Comment by amathews-amd** [comment]
> @amathews-amd , Please update test logs from your local machine if you have executed it.

Check the CI logs. 

Test1: test_flip_large_tensor_cuda (__main__.TestShapeOpsCUDA) ... test_shape_ops failed! Received signal: SIGKILL
is the failing test now.

**Comment by amathews-amd** [comment]
Single node tests work on MI100 GPU:
[PT_unittests_log_IFU-master-2022-05-17.log](https://github.com/ROCmSoftwarePlatform/pytorch/files/8757843/PT_unittests_log_IFU-master-2022-05-17.log)

**Comment by amathews-amd** [comment]
Single node tests work on gfx906 GPU:
[PT_unittests_log_IFU-master-2022-05-17_gfx906.log](https://github.com/ROCmSoftwarePlatform/pytorch/files/8759111/PT_unittests_log_IFU-master-2022-05-17_gfx906.log)

**Comment by pruthvistony** [comment]
This seems a new failure
======================================================================
FAIL: test_to (__main__.TestTorch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_torch.py", line 7662, in test_to
    self._test_to_with_layout(torch.sparse_csr)
  File "test_torch.py", line 7654, in _test_to_with_layout
    self.assertEqual(b.device, a.to(cuda, non_blocking=non_blocking).device)
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 2258, in assertEqual
    msg=msg,
  File "/opt/conda/lib/python3.7/site-packages/torch/testing/_comparison.py", line 1086, in assert_equal
    raise error_metas[0].to_error()
AssertionError: Object comparison failed: device(type='cuda', index=1) != device(type='cuda', index=0)

havent seen this failure before.
Checking upstream CI job - https://github.com/pytorch/pytorch/runs/6566209288?check_suite_focus=true
it is executed and passing.

So there could be a problem in the base master branch before IFU, But dont think this test was failing when previous IFU was done. Error is saying device comparison when only single device is enabled, confusing.

**Comment by pruthvistony** [comment]
In MI100 log
test_to (__main__.TestTorch) ... test_torch.py:7620: UserWarning: Sparse CSR tensor support is in beta state.If you miss a functionality in the sparse tensor support, please submit a feature request to https://github.com/pytorch/pytorch/issues. (Triggered internally at  /var/lib/jenkins/pytorch/aten/src/ATen/SparseCsrTensorImpl.cpp:66.)
  a = torch.tensor([[0, 1, 2], [2, 0, 3]]).to_sparse_csr()
ok

**Comment by pruthvistony** [comment]
1 failure seen
test_flip_large_tensor_cuda (__main__.TestShapeOpsCUDA) ... test_shape_ops failed! Received signal: SIGKILL

**Review by pruthvistony — APPROVED** [review]

**Pull request merged**
