### PR TITLE
[WIP] Setup rccl for PyTorch

### PR DESCRIPTION
**Pull request by jithunnair-amd**

### CODE REVIEW

**Comment by jithunnair-amd** [comment]
@iotamudelta unrelated issue, but thought I'd bring it to your attention: the caffe2 test build failed with segfault for `test_Conv2d_groups_thnn`. Is it another candidate for skipping?

**Comment by jithunnair-amd** [comment]
@iotamudelta 
```
03:19:23 + python setup.py install --user
03:19:24 Traceback (most recent call last):
03:19:24   File "setup.py", line 191, in <module>
03:19:24     from tools.setup_helpers.mkldnn import (USE_MKLDNN, MKLDNN_LIBRARY,
03:19:24 ImportError: No module named mkldnn
```
This seems like a conflict merge gone wrong? I think they removed mkldnn.py upstream.

**Comment by iotamudelta** [comment]
@jithunnair-amd yes, i needed to do some merging after the last IFU in this PR - please do check.

**Comment by jithunnair-amd** [comment]
@iotamudelta At this point, I think all the changes needed to integrate rccl into "c10->rccl" path are in this PR. Once the CI docker gets updated to have the rccl package in it, please let me know and I can make it a REQUIRED dependency in the cmake.

**Comment by iotamudelta** [comment]
@jithunnair-amd if you can resolve the conflicts, this should now be mergable with the CI update :-)

**Comment by jithunnair-amd** [comment]
I decided to reapply the changes at the top of tree instead of resolving conflicts, since they changed a few setup files. I'll file a new PR once they respond to my query about a recent change that causes a compilation issue when building distributed library on ROCm.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by iotamudelta** [comment]
@jithunnair-amd IFU completed.

**Comment by jithunnair-amd** [comment]
Reworked changes in #347, so closing this PR

**Pull request closed without merging**
