### PR TITLE
IFU master 2022 07 11

### PR DESCRIPTION
**Pull request by liligwu**
[torch_IFU_07112022_conflicts.diff.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/9086891/torch_IFU_07112022_conflicts.diff.txt)

### CODE REVIEW

**Comment by liligwu** [comment]
retest it please

**Comment by liligwu** [comment]
retest this please

**Comment by liligwu** [comment]
retest this please

**Comment by liligwu** [comment]
retest this please

**Comment by liligwu** [comment]
Tests logs for Apex, torchvision, and torchtext.
[apex_extension_unittests.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/9246161/apex_extension_unittests.txt)
[apex_ifu_distributed_unittests.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/9246162/apex_ifu_distributed_unittests.txt)
[apex_ifu_unittests.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/9246163/apex_ifu_unittests.txt)
[torchtext_test_log.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/9246164/torchtext_test_log.txt)
[torchvision_test_transforms_log.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/9246165/torchvision_test_transforms_log.txt)

**Review by jithunnair-amd — APPROVED** [review]
LGTM. Thanks for sticking through it!

**Comment by jithunnair-amd** [comment]
@liligwu I resolved a conflict in related_commits file by accepting your changes

**Comment by jithunnair-amd** [comment]
jenkins retest this please

**Comment by liligwu** [comment]
> @liligwu I resolved a conflict in related_commits file by accepting your changes

I didn't realize there is a conflict. Thank you @jithunnair-amd.

**Comment by jithunnair-amd** [comment]
CI is still misbehaving :-X .... 
1. Distributed CI doesn't seem to be running distributed tests actually: http://rocmhead.amd.com:8080/job/pytorch/job/pytorch-test-distributed-1/166/console
```
00:24:37 + sed -n '/^#### / { s///; :a; n; p; ba; }' /home/jenkins/workspace/pytorch/pytorch-test-distributed-1/test_pytorch_test_distributed_1.sh
...
00:37:16 Aug 04 05:37:16 + python test/run_test.py --continue-through-error --exclude-jit-executor --exclude-distributed-tests --shard 1 2 --verbose
```
Need to determine if this issue is seen only on CI runs for this IFU or for other PRs as well.

2. torchvision build issue on http://rocmhead.amd.com:8080/job/pytorch/job/pytorch-test-1/190/console: 
```
00:30:37 Aug 04 05:30:36     g++ -pthread -B /opt/conda/compiler_compat -Wl,--sysroot=/ -pthread -shared -B /opt/conda/compiler_compat -L/opt/conda/lib -Wl,-rpath=/opt/conda/lib -Wl,--no-as-needed -Wl,--sysroot=/ /tmp/pip-req-build-o38qjg_4/build/temp.linux-x86_64-3.7/tmp/pip-req-build-o38qjg_4/torchvision/csrc/ops/autograd/deform_conv2d_kernel.o /tmp/pip-req-build-o38qjg_4/build/temp.linux-x86_64-3.7/tmp/pip-req-build-o38qjg_4/torchvision/csrc/ops/autograd/ps_roi_align_kernel.o /tmp/pip-req-build-o38qjg_4/build/temp.linux-x86_64-3.7/tmp/pip-req-build-o38qjg_4/torchvision/csrc/ops/autograd/ps_roi_pool_kernel.o /tmp/pip-req-build-o38qjg_4/build/temp.linux-x86_64-3.7/tmp/pip-req-build-o38qjg_4/torchvision/csrc/ops/autograd/roi_align_kernel.o /tmp/pip-req-build-o38qjg_4/build/temp.linux-x86_64-3.7/tmp/pip-req-build-o38qjg_4/torchvision/csrc/ops/autograd/roi_pool_kernel.o /tmp/pip-req-build-o38qjg_4/build/temp.linux-x86_64-3.7/tmp/pip-req-build-o38qjg_4/torchvision/csrc/ops/cpu/deform_conv2d_kernel.o /tmp/pip-req-build-o38qjg_4/build/temp.linux-x86_64-3.7/tmp/pip-req-build-o38qjg_4/torchvision/csrc/ops/cpu/nms_kernel.o /tmp/pip-req-build-o38qjg_4/build/temp.linux-x86_64-3.7/tmp/pip-req-build-o38qjg_4/torchvision/csrc/ops/cpu/ps_roi_align_kernel.o /tmp/pip-req-build-o38qjg_4/build/temp.linux-x86_64-3.7/tmp/pip-req-build-o38qjg_4/torchvision/csrc/ops/cpu/ps_roi_pool_kernel.o /tmp/pip-req-build-o38qjg_4/build/temp.linux-x86_64-3.7/tmp/pip-req-build-o38qjg_4/torchvision/csrc/ops/cpu/roi_align_kernel.o /tmp/pip-req-build-o38qjg_4/build/temp.linux-x86_64-3.7/tmp/pip-req-build-o38qjg_4/torchvision/csrc/ops/cpu/roi_align_kernel_hip.o /tmp/pip-req-build-o38qjg_4/build/temp.linux-x86_64-3.7/tmp/pip-req-build-o38qjg_4/torchvision/csrc/ops/cpu/roi_pool_kernel.o /tmp/pip-req-build-o38qjg_4/build/temp.linux-x86_64-3.7/tmp/pip-req-build-o38qjg_4/torchvision/csrc/ops/deform_conv2d.o /tmp/pip-req-build-o38qjg_4/build/temp.linux-x86_64-3.7/tmp/pip-req-build-o38qjg_4/torchvision/csrc/ops/nms.o /tmp/pip-req-build-o38qjg_4/build/temp.linux-x86_64-3.7/tmp/pip-req-build-o38qjg_4/torchvision/csrc/ops/ps_roi_align.o /tmp/pip-req-build-o38qjg_4/build/temp.linux-x86_64-3.7/tmp/pip-req-build-o38qjg_4/torchvision/csrc/ops/ps_roi_pool.o /tmp/pip-req-build-o38qjg_4/build/temp.linux-x86_64-3.7/tmp/pip-req-build-o38qjg_4/torchvision/csrc/ops/quantized/cpu/qnms_kernel.o /tmp/pip-req-build-o38qjg_4/build/temp.linux-x86_64-3.7/tmp/pip-req-build-o38qjg_4/torchvision/csrc/ops/quantized/cpu/qroi_align_kernel.o /tmp/pip-req-build-o38qjg_4/build/temp.linux-x86_64-3.7/tmp/pip-req-build-o38qjg_4/torchvision/csrc/ops/roi_align.o /tmp/pip-req-build-o38qjg_4/build/temp.linux-x86_64-3.7/tmp/pip-req-build-o38qjg_4/torchvision/csrc/ops/roi_pool.o **/tmp/pip-req-build-o38qjg_4/build/temp.linux-x86_64-3.7/tmp/pip-req-build-o38qjg_4/torchvision/csrc/vision.o /tmp/pip-req-build-o38qjg_4/build/temp.linux-x86_64-3.7/tmp/pip-req-build-o38qjg_4/torchvision/csrc/vision_hip.o** -L/opt/conda/lib/python3.7/site-packages/torch/lib -lc10 -ltorch -ltorch_cpu -ltorch_python -o build/lib.linux-x86_64-3.7/torchvision/_C.so
00:30:37 Aug 04 05:30:36     /opt/conda/compiler_compat/ld: /tmp/pip-req-build-o38qjg_4/build/temp.linux-x86_64-3.7/tmp/pip-req-build-o38qjg_4/torchvision/csrc/vision_hip.o: in function `c10::impl::detail::WrapFunctionIntoRuntimeFunctor_<long (*)(), long, c10::guts::typelist::typelist<> >::operator()()':
00:30:37 Aug 04 05:30:36     /opt/conda/lib/python3.7/site-packages/torch/include/c10/util/either.h:161: multiple definition of `vision::cuda_version()'; /tmp/pip-req-build-o38qjg_4/build/temp.linux-x86_64-3.7/tmp/pip-req-build-o38qjg_4/torchvision/csrc/vision.o:/opt/conda/lib/python3.7/site-packages/torch/include/ATen/core/function_schema.h:207: first defined here
00:30:37 Aug 04 05:30:36     collect2: error: ld returned 1 exit status
00:30:37 Aug 04 05:30:36     error: command '/usr/bin/g++' failed with exit code 1
```
Need to figure out why vision.o and vision_hip.o are both being linked in.

**Comment by jithunnair-amd** [comment]
Steps followed to install torchtext:
From https://ontrack-internal.amd.com/browse/SWDEV-323546:
```
git clone https://github.com/pytorch/data.git
cd data
git checkout a73180c21f16a5a094f1a0a90fe0e696a698e6ae
python setup.py install
cd ..
git clone https://github.com/pytorch/text.git
cd text
git checkout 67bb7fcc1c60997757eeb66febf7c715269fb506
pip install cmake ninja parameterized regex expecttest spacy sacremoses nltk requests tqdm pytest-pythonpath portalocker
spacy download en_core_web_sm
python setup.py clean install
mv torchtext torchtext.bak
pytest

```

Some tests may fail at the first test run
[torchtext_test_first_run.log](https://github.com/ROCmSoftwarePlatform/frameworks-internal/files/9263445/torchtext_test_first_run.log)
but success in the second run or multiple runs
[torchtext_test_second_run.log](https://github.com/ROCmSoftwarePlatform/frameworks-internal/files/9263474/torchtext_test_second_run.log)

The failed tests in the first run may be different from the failed ones in torchtext_test_first_run.log above.

**Comment by jithunnair-amd** [comment]
Testing https://github.com/ROCmSoftwarePlatform/rocAutomation/pull/70 for distributed CI fix ....

retest this please

**Comment by jithunnair-amd** [comment]
Distributed CI run had failures:
http://rocmhead.amd.com:8080/job/pytorch/job/pytorch-test-distributed-1/169/consoleText: all tests failed with `RuntimeError: NCCL error in: /var/lib/jenkins/pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1194, unhandled cuda error, NCCL version 2.11.4`. Node-specific issue?
http://rocmhead.amd.com:8080/job/pytorch/job/pytorch-test-distributed-2/162/consoleText: `test_data_parallel*` tests failed. Need to cherry-pick fix in https://github.com/pytorch/pytorch/pull/78824

**Comment by liligwu** [comment]
The distributed tests log (tested locally)
[PT_unittests_log_IFU-master-2022-07-11_distributed.txt](https://github.com/ROCmSoftwarePlatform/pytorch/files/9270058/PT_unittests_log_IFU-master-2022-07-11_distributed.txt)

**Comment by jithunnair-amd** [comment]
jenkins retest this please

**Comment by jithunnair-amd** [comment]
CI run http://rocmhead.amd.com:8080/job/pytorch/job/pytorch-ci/272/ passed all tests except `test_multiple_outputs (__main__.TestTensorExprFuser)`, which is a known issue on MI200: https://ontrack-internal.amd.com/browse/SWDEV-349199

**Pull request merged**
